
import React, { createContext, useContext, useState, ReactNode } from 'react';

import type { Language } from '@/types';

// 1. Define the Master Translation Schema (using zh-TW as source of truth)
const zhTwTranslations = {
  'system.title': 'AVOS # 符文技藝',
  'system.subtitle': 'ESG 自演化管理系統 v6.0',
  'dashboard.overview': '數據總覽',
  'dashboard.emissions': '碳排放分析',
  'dashboard.mentorship': '師徒系統',
  'dashboard.progress': '學習進度',
  'dashboard.resonance': '共鳴度',
  'monitor.title': '系統感知監控',
  'monitor.cpu': '運算核心',
  'monitor.memory': '記憶體',
  'monitor.entropy': '熵值',
  'monitor.healthy': '系統正常',
  'monitor.critical': '系統異常',
  'goals.title': '認知目標追蹤',
  'goals.active': '活躍目標',
  'goals.add': '輸入新目標...',
  'matrix.title': '終始矩陣 (Alpha-Omega)',
  'matrix.alpha': '起源 (Alpha)',
  'matrix.omega': '終焉 (Omega)',
  'matrix.cycle': '循環',
  'matrix.status': '狀態',
  'matrix.duration': '耗時',
  'rune.level': '主權等級',
  'rune.vault': '資產金庫',
  'rune.yield': '預估產出',
  'rune.ledger': '已驗證帳本',

  // CyberESG
  'cyber.title': 'Cyber-ESG 戰略主權系統',
  'cyber.subtitle': 'NEO-SOVEREIGN INTELLIGENCE HUB V6.0',
  'cyber.level': '戰略等級',
  'cyber.palace': '記憶宮殿：水平矩陣',
  'cyber.runes': '符文協同系統',
  'cyber.impact': '影響力核心評分',
  'cyber.impact.desc': 'Impact Center Scoreboard',
  'cyber.verified': '數據已驗算',
  'cyber.strategy': '戰略決策自動化',
  'cyber.principles.trace': '可溯源',
  'cyber.principles.track': '可追蹤',
  'cyber.principles.calc': '可驗算',
  'cyber.principles.lock': '不可竄改',

  // Learning Alchemy (New)
  'alchemy.title': 'ESG All In One',
  'alchemy.subtitle': 'Learning Alchemy',
  'alchemy.stage.theory': '知識具象化 (Tangible)',
  'alchemy.stage.theory.desc': '將抽象的 ESG 概念轉化為具體的知識資產。為它賦予一個 UUID，這就是它在數位世界中的靈魂編號。',
  'alchemy.stage.theory.asset_def': '資產定義',
  'alchemy.stage.example': '知識溯源 (Traceable)',
  'alchemy.stage.example.desc': '真正的知識必須經得起考驗。連結至真實的企業案例或國際標準來源。',
  'alchemy.stage.practice': '實作歷程 (Trackable)',
  'alchemy.stage.practice.desc': '你的每一次操作、計算與模擬，都將被記錄在區塊鏈上，成為不可抹滅的成長軌跡。',
  'alchemy.stage.confirm': '透明驗證 (Transparent)',
  'alchemy.stage.confirm.desc': '攤開黑箱。我們驗證所有的計算邏輯與合規標準。',
  'alchemy.stage.sealing': '資產封印儀式 (Trustworthy)',
  'alchemy.stage.sealing.desc': '將您的學習成果雜湊鎖定，轉化為永恆的數位資產。',
  'alchemy.stage.sealing.action': '執行封印 (Seal Asset)',
  'alchemy.stage.sealing.sealed': '已封印 & 驗證 (SEALED)',
  'alchemy.concept.tangible': 'Tangible (具象)',
  'alchemy.concept.traceable': 'Traceable (溯源)',
  'alchemy.concept.trackable': 'Trackable (追蹤)',
  'alchemy.concept.transparent': 'Transparent (透明)',
  'alchemy.concept.trustworthy': 'Trustworthy (不可篡改)',
  'alchemy.card.desc': '[ESG 知識模組]\n主題: {title}\n\n驗證來源: {ref}。\n核心概念已結晶為可用的服務模組。',
  'alchemy.card.flavor.case': '理論已由 {ref} 的足跡所驗證。',
  'alchemy.card.flavor.theory': '純粹的理論，等待現實的重量來檢驗。',
  'alchemy.card.effect.unlock': '解鎖功能: {title}',
  'alchemy.card.effect.boost': '提升共鳴度 {value} 點。',
  'alchemy.deck.button': '我的牌組 (My Deck)',
  'alchemy.deck.title': 'Omni Deck Storage',
  'alchemy.deck.empty': '尚未封印資產。完成煉金過程以鍛造卡牌。',
  'alchemy.deck.equip': '裝備 (EQUIP)',
  'alchemy.deck.equipped': '已裝備 (EQUIPPED)',
  'alchemy.next': '下一步',

  // Dr. Thoth Messages
  'thoth.theory': '知識若無身分，便只是資訊。我們現在賦予它 UUID，讓它在你的記憶聖所中獲得實體。',
  'thoth.example': '看這些真實的足跡。每一個範例都具備可溯源的基因，讓你的學習不再建立於空中樓閣。',
  'thoth.practice': '動手吧！我已為你的實作過程安插了生命週期標籤。你解決問題的路徑，就是這項資產的成長紀錄。',
  'thoth.confirm': '拒絕黑箱！這是法規與算法的共鳴。當你能驗證公式的透明度，這份知識才具備純度。',
  'thoth.sealing': '儀式完成。這份知識已永久與你的 UUID 綁定，狀態已標記為 Trustworthy。它現在是你的數位資產，永恆不可篡改。',
  'thoth.default': '讓我們開始煉金之旅。',

  // Global UI
  'ui.theme.day': '日時光模式',
  'ui.theme.night': '夜幽光模式',
  'ui.language': '語言',
  'ui.search.placeholder': '智能檢索 ESG 知識資產...',
  'ui.status.title': '系統狀態',
  'ui.status.stable': '穩定執行',
  'ui.profile': '用戶資料',
  'ui.logout': '登出系統',
  'ui.settings': '全域設定',
  'profile.edit': '編輯資料',
  'profile.save': '保存變更',
  'profile.role': '角色權限',

  // Stitch Themes
  'theme.aqua': 'Aqua 青',
  'theme.aqua.desc': '上善若水，善利萬物而不爭。流程與透明度的象徵。',
  'theme.gold': 'Gold 金',
  'theme.gold.desc': '堅固結構，永恆價值。可信與不可篡改的象徵。',
  'theme.mist': 'Mist 霧',
  'theme.mist.desc': '隱密與流動，潛移默化。',
  'theme.ocean': 'Ocean 洋',
  'theme.ocean.desc': '深邃潛力，廣納百川。',
  'theme.void': 'Void 虛',
  'theme.void.desc': '無限可能，歸於虛無。',
  'ui.mode.day': '日時光',
  'ui.mode.night': '夜幽光',
  'ui.mode.system': '系統跟隨',
  'ui.mode.label': '顯示模式',

  // Stitch Showcase Hero
  'stitch.hero.title': '五種原子風格',
  'stitch.hero.subtitle': '探索上善與永續的交會點，透過五種獨特的視覺語言。',
  'stitch.footer': 'InfoOne x Google Stitch Design System © 2026',
  'stitch.functions.title': '第一波：十項核心功能',
  'stitch.functions.subtitle': '以 Google Stitch 打造的 InfoOne 完整生態系服務矩陣。',

  // First Wave Functions
  'stitch.func.hub': '數位分身',
  'stitch.func.hub.desc': '您的永續旅程起點。具象化您的數據人格與成長軌跡。',
  'stitch.func.report': '永續報告',
  'stitch.func.report.desc': '自動化生成符合 GRI/SASB 標準的專業報告，確保資訊確信度。',
  'stitch.func.intel': '商情偵測',
  'stitch.func.intel.desc': '透過 AI 實時監控市場趨勢與風險，提供精準的決策支持。',
  'stitch.func.village': '善向永續村',
  'stitch.func.village.desc': '沈浸式永續經營模擬，在遊戲中學習資源管理與社會責任。',
  'stitch.func.academy': '永續學院',
  'stitch.func.academy.desc': 'Berkeley 認證課程與專業知識庫，為您的職涯加值。',
  'stitch.func.ai': '奧秘圓通',
  'stitch.func.ai.desc': '全方位的 AI 協作夥伴，為您調和數據、洞察與行動。',
  'stitch.func.alchemy': '學習煉金術',
  'stitch.func.alchemy.desc': '將學習成果轉化為不可篡改的數位資產與證書。',
  'stitch.func.vault': '我的個人儲存倉',
  'stitch.func.vault.desc': '系統化的 ESG 知識管理系統，隨時調用經過驗證的資訊。',
  'stitch.func.nexus': '影響力連結',
  'stitch.func.nexus.desc': '連結個人行動與全球目標，視覺化您的永續影響力。',
  'stitch.func.northstar': '我的北極星',
  'stitch.func.northstar.desc': '設定並追蹤您的永續願景與長期目標，指引前行方向。',

  // MVP Hub
  'mvp.hub.title': '萬能全功能中心',
  'mvp.hub.subtitle': 'InfoOne MVP 全方位管理與覺醒入口',
  'mvp.modules.report.title': '永續報告',
  'mvp.modules.report.desc': '自動化抓取各節點數據，生成符合 GRI, SASB 規範的永續報告書。',
  'mvp.modules.intelligence.title': '商業偵情',
  'mvp.modules.intelligence.desc': 'Dr. Thoth 每日監控 30+ 標竿網站。市場競爭力分析與風險預警。',
  'mvp.modules.avatar.title': '數位分身',
  'mvp.modules.avatar.desc': '你的「第二自己」。靈魂刻印、提示詞聖殿與決策代行。',
  'mvp.modules.village.title': '善向永續村',
  'mvp.modules.village.desc': 'ARPG 遊戲化界面，將 ESG 指標轉化為建設能量。',
  'mvp.modules.backend.title': '萬能後台',
  'mvp.modules.backend.desc': '系統深度監控、數據管理與工程師專用主控台。',
  'mvp.modules.personal.title': '個人主控中心',
  'mvp.modules.personal.desc': '管理您的主權身份、個人儲存倉與北極星共鳴設定。',
  'mvp.village.tasks': '任務與成長',
  'mvp.village.phase1': '第一階段：永續數據溯源 [ISO-14064]',
  'mvp.village.phase2': '第二階段：商業情報獵取 [Dr. Thoth]',
  'mvp.village.data': '永續數據',
  'mvp.village.intelligence': '商業情資',
  'mvp.village.vault': '量子金庫',
  'mvp.village.forest': '永續森林',
  'mvp.village.twin': '數位分身',
  'avatar.title': '數位分身中心',
  'avatar.stats.title': '角色屬性',
  'avatar.stats.strength': '力量',
  'avatar.stats.wisdom': '智慧',
  'avatar.stats.agility': '敏捷',
  'avatar.stats.charisma': '魅力',
  'avatar.stats.endurance': '耐力',
  'avatar.skills.title': '技能系統',
  'avatar.equipment.title': '裝備欄',
  'avatar.achievements.title': '成就系統',
  'avatar.badges.title': '徽章收藏',
  'avatar.growth.title': '成長軌跡',
  'avatar.tabs.stats': '屬性',
  'avatar.tabs.skills': '技能',
  'avatar.tabs.equipment': '裝備',
  'avatar.tabs.achievements': '成就',
  'avatar.tabs.badges': '徽章',
  'intel.title': '永續商情中心',
  'intel.status.scanning': '頻率掃描中...',
  'intel.status.active': '全域視覺已激活',
  'intel.sentinel.title': '哨兵每日觀察',
  'intel.impact_surface': '實時 ESG 影響力曲面',
  'intel.global_flow': '全球情資流',
  'intel.convert_task': '轉換為任務',
  'intel.syncing': '正在與大地之心同步中...',
  'omni.dev.mapping.active': '奧秘映射激活',
  'omni.dev.protocol.standby': '5T 協議待命',
  'omni.console.title': '奧秘標籤控制台',
  'omni.console.governance': '系統治理模式',
  'omni.console.spectrum': '奧秘標籤光譜',


  'mvp.metrics.overview': '指標概覽',
  'mvp.metrics.data': '數據盤查',
  'mvp.metrics.audit': '合規審核',
  'mvp.metrics.report': '報告生成',
  'mvp.metrics.trace': '供應鏈地圖',
  'mvp.metrics.origin': '情資溯源庫',
  'mvp.metrics.rival': '敵情偵探',
  'mvp.metrics.law': '法規監控',
  'mvp.metrics.awakening': '靈魂喚醒',
  'mvp.metrics.forge': '技能演化',
  'mvp.metrics.agency': '決策代行',
  'mvp.metrics.omni': '萬能轉換',
  'mvp.metrics.imprint': 'UUID 刻印',
  'mvp.metrics.contract': '權限契約',
  'mvp.metrics.audit_log': '行為審計',
  'mvp.metrics.badge': '魂徽牆',
  'mvp.metrics.map': '建設地圖',
  'mvp.metrics.eco': '共榮生態',
  'mvp.metrics.energy': '資源轉換',
  'mvp.metrics.guild': '任務公會',
  'mvp.metrics.entropy': '熵減儀表',
  'mvp.metrics.net': '代理網絡',
  'mvp.metrics.review': '聖典審查',
  'mvp.metrics.i18n': '多語映射',
  'mvp.nav.core': 'MVP 核心',
  'mvp.nav.hub': '萬能全功能中心',
};





// 2. Type definition derived from zh-TW keys
export type TranslationKey = keyof typeof zhTwTranslations;

// 3. English Translations (Strictly typed to match keys)
const enUsTranslations: Record<TranslationKey, string> = {
  'system.title': 'AVOS # Rune Craft',
  'system.subtitle': 'ESG Self-Evolving System v6.0',
  'dashboard.overview': 'Overview',
  'dashboard.emissions': 'Emissions Analysis',
  'dashboard.mentorship': 'Mentorship System',
  'dashboard.progress': 'Learning Progress',
  'dashboard.resonance': 'Resonance',
  'monitor.title': 'System Perception',
  'monitor.cpu': 'CPU Core',
  'monitor.memory': 'Memory',
  'monitor.entropy': 'Entropy',
  'monitor.healthy': 'System Healthy',
  'monitor.critical': 'System Critical',
  'goals.title': 'Cognitive Goals',
  'goals.active': 'Active Goals',
  'goals.add': 'Add new goal...',
  'matrix.title': 'Alpha-Omega Matrix',
  'matrix.alpha': 'Alpha (Start)',
  'matrix.omega': 'Omega (End)',
  'matrix.cycle': 'Cycle',
  'matrix.status': 'Status',
  'matrix.duration': 'Duration',
  'rune.level': 'Sovereignty Level',
  'rune.vault': 'Asset Vault',
  'rune.yield': 'Est. Yield',
  'rune.ledger': 'Verified Ledger',

  // CyberESG
  'cyber.title': 'Cyber-ESG Sovereign Strategy System',
  'cyber.subtitle': 'NEO-SOVEREIGN INTELLIGENCE HUB V6.0',
  'cyber.level': 'Strategy Level',
  'cyber.palace': 'Memory Palace: Horizon Matrix',
  'cyber.runes': 'Rune Synergy',
  'cyber.impact': 'Impact Core Score',
  'cyber.impact.desc': 'Impact Center Scoreboard',
  'cyber.verified': 'Data Verified',
  'cyber.strategy': 'Strategy Automation',
  'cyber.principles.trace': 'Traceable',
  'cyber.principles.track': 'Trackable',
  'cyber.principles.calc': 'Calculable',
  'cyber.principles.lock': 'Immutable',

  // Learning Alchemy
  'alchemy.title': 'ESG All In One',
  'alchemy.subtitle': 'Learning Alchemy',
  'alchemy.stage.theory': 'Knowledge Tangibility (Tangible)',
  'alchemy.stage.theory.desc': 'Transmute abstract ESG concepts into concrete knowledge assets. Assign it a UUID, its soul number in the digital world.',
  'alchemy.stage.theory.asset_def': 'Asset Definition',
  'alchemy.stage.example': 'Knowledge Traceability (Traceable)',
  'alchemy.stage.example.desc': 'True knowledge must withstand scrutiny. Link to real corporate cases or international standard sources.',
  'alchemy.stage.practice': 'Implementation Trackability (Trackable)',
  'alchemy.stage.practice.desc': 'Every action, calculation, and simulation you make is recorded on the blockchain as an indelible growth trajectory.',
  'alchemy.stage.confirm': 'Transparency Verification (Transparent)',
  'alchemy.stage.confirm.desc': 'Open the black box. We verify all calculation logic and compliance standards.',
  'alchemy.stage.sealing': 'Asset Sealing Ritual (Trustworthy)',
  'alchemy.stage.sealing.desc': 'Hash-lock your learning outcomes, transforming them into eternal digital assets.',
  'alchemy.stage.sealing.action': 'Seal Asset',
  'alchemy.stage.sealing.sealed': 'SEALED & VERIFIED',
  'alchemy.concept.tangible': 'Tangible',
  'alchemy.concept.traceable': 'Traceable',
  'alchemy.concept.trackable': 'Trackable',
  'alchemy.concept.transparent': 'Transparent',
  'alchemy.concept.trustworthy': 'Trustworthy',
  'alchemy.card.desc': '[ESG Knowledge Module]\nSubject: {title}\n\nVerified by: {ref}. \nCore concept crystallized into a usable service module.',
  'alchemy.card.flavor.case': 'Theory proven by the footprints of {ref}.',
  'alchemy.card.flavor.theory': 'Pure theory, awaiting the weight of reality.',
  'alchemy.card.effect.unlock': 'Unlocks feature: {title}',
  'alchemy.card.effect.boost': 'Increases resonance by {value}.',
  'alchemy.deck.button': 'My Deck',
  'alchemy.deck.title': 'Omni Deck Storage',
  'alchemy.deck.empty': 'No assets sealed yet. Complete the alchemy process to forge cards.',
  'alchemy.deck.equip': 'EQUIP',
  'alchemy.deck.equipped': 'EQUIPPED',
  'alchemy.next': 'Next Step',

  // Dr. Thoth
  'thoth.theory': 'Knowledge without identity is merely data. We now endow it with a UUID, giving it substance in your memory sanctuary.',
  'thoth.example': 'Look at these real footprints. Every example possesses traceable genes, ensuring your learning isn\'t built on castles in the air.',
  'thoth.practice': 'Take action! I have inserted lifecycle tags into your implementation process. Your path to solving problems is the growth record of this asset.',
  'thoth.confirm': 'Reject the black box! As laws resonate with algorithms, only when you can verify the transparency of the formula does knowledge possess purity.',
  'thoth.sealing': 'Ritual complete. This knowledge is permanently bound to your UUID, verified as Trustworthy. It is your digital asset.',
  'thoth.default': 'Let us begin the alchemy journey.',

  // Global UI
  'ui.theme.day': 'Day Mode',
  'ui.theme.night': 'Night Mode',
  'ui.language': 'Language',
  'ui.search.placeholder': 'Search ESG Intelligence Assets...',
  'ui.status.title': 'System Status',
  'ui.status.stable': 'Stable Operation',
  'ui.profile': 'User Profile',
  'ui.logout': 'Logout',
  'ui.settings': 'Global Settings',
  'profile.edit': 'Edit Profile',
  'profile.save': 'Save Changes',
  'profile.role': 'Role & Permissions',

  // Stitch Themes
  'theme.aqua': 'Aqua',
  'theme.aqua.desc': 'Water-like nature, benefiting all things without contention. Symbol of flow and transparency.',
  'theme.gold': 'Gold',
  'theme.gold.desc': 'Solid structure, eternal value. Symbol of trust and immutability.',
  'theme.mist': 'Mist',
  'theme.mist.desc': 'Subtle and flowing, evolving unseen.',
  'theme.ocean': 'Ocean',
  'theme.ocean.desc': 'Deep potential, embracing all rivers.',
  'theme.void': 'Void',
  'theme.void.desc': 'Infinite possibilities, returning to emptiness.',
  'ui.mode.day': 'Day Mode',
  'ui.mode.night': 'Night Mode',
  'ui.mode.system': 'System Follow',
  'ui.mode.label': 'Display Mode',

  // Stitch Showcase Hero
  'stitch.hero.title': 'The Five Atomic Styles',
  'stitch.hero.subtitle': 'Exploring the intersection of benevolence and sustainability through five distinct visual dialects.',
  'stitch.footer': 'InfoOne x Google Stitch Design System © 2026',
  'stitch.functions.title': 'First Wave: Ten Core Functions',
  'stitch.functions.subtitle': 'The complete InfoOne ecosystem service matrix built with Google Stitch.',

  // First Wave Functions
  'stitch.func.hub': 'Personal Hub',
  'stitch.func.hub.desc': 'Your starting point for the sustainability journey. Central dashboard integrating all data, tasks, and achievements.',
  'stitch.func.report': 'ESG Reporting Center',
  'stitch.func.report.desc': 'Automated generation of professional reports compliant with GRI/SASB standards, ensuring information assurance.',
  'stitch.func.intel': 'Market Intelligence',
  'stitch.func.intel.desc': 'Real-time monitoring of market trends and risks via AI, providing precise decision support.',
  'stitch.func.village': 'Sustainable Village',
  'stitch.func.village.desc': 'Immersive sustainability management simulation, learning resource management and social responsibility in a game.',
  'stitch.func.academy': 'Sustainability Academy',
  'stitch.func.academy.desc': 'Berkeley certified courses and professional knowledge base, adding value to your career.',
  'stitch.func.ai': 'Omni-Harmonizer',
  'stitch.func.ai.desc': 'Your holistic AI collaborator, harmonizing data, insights, and actions.',
  'stitch.func.alchemy': 'Learning Alchemy',
  'stitch.func.alchemy.desc': 'Transform learning outcomes into immutable digital assets and certificates.',
  'stitch.func.vault': 'My Personal Vault',
  'stitch.func.vault.desc': 'Systematic ESG knowledge management system, accessing verified information at any time.',
  'stitch.func.nexus': 'Impact Nexus',
  'stitch.func.nexus.desc': 'Linking personal actions with global goals, visualizing your sustainability impact.',
  'stitch.func.northstar': 'My North Star',
  'stitch.func.northstar.desc': 'Set and track your sustainability vision and long-term goals, guiding your path forward.',

  // MVP Hub
  'mvp.hub.title': 'Omni All-In-One Hub',
  'mvp.hub.subtitle': 'Universal Entrance for InfoOne MVP & Awakening',
  'mvp.modules.report.title': 'Sustainability Report',
  'mvp.modules.report.desc': 'Automated data gathering and report generation compliant with GRI/SASB.',
  'mvp.modules.intelligence.title': 'Business Intelligence',
  'mvp.modules.intelligence.desc': 'Dr. Thoth monitoring 30+ benchmark sites. Market analysis and risk alerts.',
  'mvp.modules.avatar.title': 'Digital Twin',
  'mvp.modules.avatar.desc': 'Your "Second Self". Soul imprinting, prompt sanctuary, and agentic agency.',
  'mvp.modules.village.title': 'Benevolent Village',
  'mvp.modules.village.desc': 'ARPG gamified interface transforming ESG metrics into construction energy.',
  'mvp.modules.backend.title': 'Omni Backend',
  'mvp.modules.backend.desc': 'Deep monitoring, data management, and engineer system console.',
  'mvp.modules.personal.title': 'Personal Hub',
  'mvp.modules.personal.desc': 'Manage sovereign identity, personal storage, and North Star resonance.',
  'mvp.village.tasks': 'Tasks & Growth',
  'mvp.village.phase1': 'Phase 1: Sustainability Data Tracing [ISO-14064]',
  'mvp.village.phase2': 'Phase 2: Business Intelligence Hunting [Dr. Thoth]',
  'mvp.village.data': 'Sus-Data',
  'mvp.village.intelligence': 'Biz-Intel',
  'mvp.village.vault': 'Quantum Vault',
  'mvp.village.forest': 'Sus-Forest',
  'mvp.village.twin': 'Agentic Twin',
  'avatar.title': 'Digital Twin Center',
  'avatar.stats.title': 'Character Stats',
  'avatar.stats.strength': 'Strength',
  'avatar.stats.wisdom': 'Wisdom',
  'avatar.stats.agility': 'Agility',
  'avatar.stats.charisma': 'Charisma',
  'avatar.stats.endurance': 'Endurance',
  'avatar.skills.title': 'Skill System',
  'avatar.equipment.title': 'Equipment',
  'avatar.achievements.title': 'Achievements',
  'avatar.badges.title': 'Badges',
  'avatar.growth.title': 'Growth Track',
  'avatar.tabs.stats': 'Stats',
  'avatar.tabs.skills': 'Skills',
  'avatar.tabs.equipment': 'Equip',
  'avatar.tabs.achievements': 'Achi',
  'avatar.tabs.badges': 'Badges',
  'intel.title': 'Market Intel Center',
  'intel.status.scanning': 'Scanning...',
  'intel.status.active': 'Omni-Vision Active',
  'intel.sentinel.title': 'Sentinel Observation',
  'intel.impact_surface': 'Real-time ESG Impact Surface',
  'intel.global_flow': 'Global Intelligence',
  'intel.convert_task': 'CONVERT TO TASK',
  'intel.syncing': 'Syncing with Gaia...',
  'omni.dev.mapping.active': 'Omni Mapping Active',
  'omni.dev.protocol.standby': '5T Protocol Standby',
  'omni.console.title': 'Omni Tag Console',
  'omni.console.governance': 'System Governance Mode',
  'omni.console.spectrum': 'Omni Tag Spectrum',


  'mvp.metrics.overview': 'Metrics Overview',
  'mvp.metrics.data': 'Data Inventory',
  'mvp.metrics.audit': 'Compliance Audit',
  'mvp.metrics.report': 'Report Gen',
  'mvp.metrics.trace': 'Trace Chain',
  'mvp.metrics.origin': 'Source Origin',
  'mvp.metrics.rival': 'Competitor BM',
  'mvp.metrics.law': 'Regulatory',
  'mvp.metrics.awakening': 'The Awakening',
  'mvp.metrics.forge': 'Skill Forge',
  'mvp.metrics.agency': 'Agency Node',
  'mvp.metrics.omni': 'Omni Converter',
  'mvp.metrics.imprint': 'Imprinting',
  'mvp.metrics.contract': 'Policy Matrix',
  'mvp.metrics.audit_log': 'Activity Log',
  'mvp.metrics.badge': 'Soul Badge',
  'mvp.metrics.map': 'Village Map',
  'mvp.metrics.eco': 'Ecosystem',
  'mvp.metrics.energy': 'Energy Engine',
  'mvp.metrics.guild': 'Mission Guild',
  'mvp.metrics.entropy': 'Entropy Dash',
  'mvp.metrics.net': 'Agent Orchest',
  'mvp.metrics.review': 'Arch Review',
  'mvp.metrics.i18n': 'I18n Mapping',
  'mvp.nav.core': 'MVP Core',
  'mvp.nav.hub': 'Omni All-In-One Hub',
};





// 4. Korean Translations (Strictly typed to match keys)
const koKrTranslations: Record<TranslationKey, string> = {
  'system.title': 'AVOS # 룬 기술',
  'system.subtitle': 'ESG 자가 진화 관리 시스템 v6.0',
  'dashboard.overview': '데이터 개요',
  'dashboard.emissions': '탄소 배출 분석',
  'dashboard.mentorship': '멘토십 시스템',
  'dashboard.progress': '학습 진척도',
  'dashboard.resonance': '공명도',
  'monitor.title': '시스템 지각 모니터ING',
  'monitor.cpu': '연산 핵심',
  'monitor.memory': '메모리',
  'monitor.entropy': '엔트로피',
  'monitor.healthy': '시스템 정상',
  'monitor.critical': '시스템 이상',
  'goals.title': '인지 목표 추적',
  'goals.active': '활성 목표',
  'goals.add': '새 목표 입력...',
  'matrix.title': '알파-오메가 매트릭스',
  'matrix.alpha': '기원 (Alpha)',
  'matrix.omega': '종결 (Omega)',
  'matrix.cycle': '사이클',
  'matrix.status': '상태',
  'matrix.duration': '소요 시간',
  'rune.level': '소버린 레벨',
  'rune.vault': '자산 금고',
  'rune.yield': '예상 산출',
  'rune.ledger': '검증된 장부',

  // CyberESG
  'cyber.title': 'Cyber-ESG 전략 소버린 시스템',
  'cyber.subtitle': 'NEO-SOVEREIGN INTELLIGENCE HUB V6.0',
  'cyber.level': '전략 레벨',
  'cyber.palace': '기억의 궁전: 수평 매트릭스',
  'cyber.runes': '룬 시너지 시스템',
  'cyber.impact': '영향력 핵심 점수',
  'cyber.impact.desc': 'Impact Center Scoreboard',
  'cyber.verified': '데이터 검증됨',
  'cyber.strategy': '전략적 의사결정 자동화',
  'cyber.principles.trace': '추적성 (Traceable)',
  'cyber.principles.track': '추적 가능 (Trackable)',
  'cyber.principles.calc': '연산 가능 (Calculable)',
  'cyber.principles.lock': '위변조 불가 (Immutable)',

  // Learning Alchemy
  'alchemy.title': 'ESG All In One',
  'alchemy.subtitle': '학습 연금술 (Learning Alchemy)',
  'alchemy.stage.theory': '지식의 구체화 (Tangible)',
  'alchemy.stage.theory.desc': '추상적인 ESG 개념을 구체적인 지식 자산으로 전환합니다. UUID를 부여하여 디지털 세계에서의 고유 매핑을 생성합니다.',
  'alchemy.stage.theory.asset_def': '자산 정의',
  'alchemy.stage.example': '지식溯源 (Traceable)',
  'alchemy.stage.example.desc': '진정한 지식은 검증을 견뎌야 합니다. 실제 기업 사례나 국제 표준 소스에 연결하세요.',
  'alchemy.stage.practice': '실행 추적성 (Trackable)',
  'alchemy.stage.practice.desc': '당신의 모든 조작, 계산 및 시뮬레이션은 블록체인에 기록되어 지워지지 않는 성장 궤적이 됩니다.',
  'alchemy.stage.confirm': '투명성 검증 (Transparent)',
  'alchemy.stage.confirm.desc': '블랙박스를 여세요. 모든 계산 로직과 규정 준수 표준을 검증합니다.',
  'alchemy.stage.sealing': '자산 봉인 의식 (Trustworthy)',
  'alchemy.stage.sealing.desc': '학습 성과를 해시 잠금하여 영원한 디지털 자산으로 전환합니다.',
  'alchemy.stage.sealing.action': '자산 봉인',
  'alchemy.stage.sealing.sealed': '봉인 및 검증됨 (SEALED)',
  'alchemy.concept.tangible': 'Tangible (구체적)',
  'alchemy.concept.traceable': 'Traceable (溯源)',
  'alchemy.concept.trackable': 'Trackable (추적)',
  'alchemy.concept.transparent': 'Transparent (투명)',
  'alchemy.concept.trustworthy': 'Trustworthy (신뢰)',
  'alchemy.card.desc': '[ESG 지식 모듈]\n주제: {title}\n\n검증 소스: {ref}。\n핵심 개념이 사용 가능한 서비스 모듈로 결정화되었습니다.',
  'alchemy.card.flavor.case': '이론은 {ref}의 기록에 의해 검증되었습니다.',
  'alchemy.card.flavor.theory': '순수한 이론, 현실의 무게로 검증되기를 기다립니다.',
  'alchemy.card.effect.unlock': '기능 해제: {title}',
  'alchemy.card.effect.boost': '공명도 {value} 점 상승.',
  'alchemy.deck.button': '내 덱',
  'alchemy.deck.title': 'Omni Deck Storage',
  'alchemy.deck.empty': '아직 봉인된 자산이 없습니다. 연금술 과정을 완료하여 카드를 제작하세요.',
  'alchemy.deck.equip': '장착',
  'alchemy.deck.equipped': '학습 완료',
  'alchemy.next': '다음 단계',

  // Dr. Thoth
  'thoth.theory': '정체성 없는 지식은 정보일 뿐입니다. 이제 UUID를 부여하여 당신의 기억 성소에서 실체를 갖게 합니다.',
  'thoth.example': '이 실제 기록을 보세요. 모든 예시는 추적 가능한 유전자를 가지고 있어 당신의 학습이 사상누각이 되지 않도록 합니다.',
  'thoth.practice': '시작하세요! 당신의 구현 과정에 생명주기 태그를 삽입했습니다. 문제를 해결하는 경로가 바로 이 자산의 성장 기록입니다.',
  'thoth.confirm': '블랙박스를 거부하세요! 이것은 법규와 알고리즘의 공명입니다. 공식의 투명성을 검증할 수 있을 때 비로소 지식은 순도를 갖게 됩니다.',
  'thoth.sealing': '의식이 완료되었습니다. 이 지식은 당신의 UUID와 영구적으로 결합되어 Trustworthy로 표시되었습니다. 이제 당신의 디지털 자산입니다.',
  'thoth.default': '연금술 여행을 시작해 봅시다.',

  // Global UI
  'ui.theme.day': '낮 모드',
  'ui.theme.night': '밤 모드',
  'ui.language': '언어',
  'ui.search.placeholder': 'ESG 지식 자산 검색...',
  'ui.status.title': '시스템 상태',
  'ui.status.stable': '안정적으로 실행 중',
  'ui.profile': '사용자 프로필',
  'ui.logout': '로그아웃',
  'ui.settings': '전역 설정',
  'profile.edit': '프로필 편집',
  'profile.save': '변경 사항 저장',
  'profile.role': '역할 및 권한',

  // Stitch Themes
  'theme.aqua': '아쿠아 (Aqua)',
  'theme.aqua.desc': '상선약수(上善若水), 만물을 이롭게 하며 다투지 않음. 흐름과 투명성의 상징.',
  'theme.gold': '골드 (Gold)',
  'theme.gold.desc': '견고한 구조, 영원한 가치. 신뢰와 불변성의 상징.',
  'theme.mist': '미스트 (Mist)',
  'theme.mist.desc': '은밀하게 흐르는 변화.',
  'theme.ocean': '오션 (Ocean)',
  'theme.ocean.desc': '깊은 잠재력, 모든 강을 포용함.',
  'theme.void': '보이드 (Void)',
  'theme.void.desc': '무한한 가능성, 허공으로의 회귀.',
  'ui.mode.day': '라이트 모드',
  'ui.mode.night': '다크 모드',
  'ui.mode.system': '시스템 설정',
  'ui.mode.label': '화면 모드',

  // Stitch Showcase Hero
  'stitch.hero.title': '다섯 가지 원자 스타일',
  'stitch.hero.subtitle': '선(善)과 지속가능성의 교차점을 다섯 가지 독특한 시각적 언어로 탐구합니다.',
  'stitch.footer': 'InfoOne x Google Stitch Design System © 2026',
  'stitch.functions.title': '첫 번째 물결: 10대 핵심 기능',
  'stitch.functions.subtitle': 'Google Stitch로 구축된 InfoOne의 완전한 생태계 서비스 매트릭스.',

  // First Wave Functions
  'stitch.func.hub': '디지털 아바타',
  'stitch.func.hub.desc': '지속가능한 여정의 시작점. 데이터 페르소나와 성장 궤적을 시각화합니다.',
  'stitch.func.report': '지속가능성 보고',
  'stitch.func.report.desc': '데이터 신뢰성을 보장하는 GRI/SASB 준수 전문 보고서 자동 생성.',
  'stitch.func.intel': '시장 정보',
  'stitch.func.intel.desc': '정밀한 의사결정 지원을 위한 AI 기반 시장 동향 및 리스크 실시간 모니터링.',
  'stitch.func.village': '지속가능한 마을',
  'stitch.func.village.desc': '자원 관리와 사회적 책임을 배우는 몰입형 지속가능성 경영 시뮬레이션.',
  'stitch.func.academy': '지속가능성 아카데미',
  'stitch.func.academy.desc': '커리어 가치를 높이는 버클리 인증 과정 및 전문 지식 베이스.',
  'stitch.func.ai': '옴니 하모나이저',
  'stitch.func.ai.desc': '데이터, 통찰력, 행동을 조화시키는 포괄적인 AI 협력 파트너.',
  'stitch.func.alchemy': '학습 연금술',
  'stitch.func.alchemy.desc': '학습 성과를 불변의 디지털 자산 및 인증서로 변환합니다.',
  'stitch.func.vault': '나의 개인 금고',
  'stitch.func.vault.desc': '검증된 정보를 언제든지 호출할 수 있는 체계적인 ESG 지식 관리 시스템.',
  'stitch.func.nexus': '임팩트 넥서스',
  'stitch.func.nexus.desc': '개인의 행동을 글로벌 목표와 연결하여 지속 가능성 영향력을 시각화합니다.',
  'stitch.func.northstar': '나의 북극성',
  'stitch.func.northstar.desc': '지속가능성 비전과 장기 목표를 설정하고 추적하여 나아갈 방향을 제시합니다.',

  // MVP Hub (Fallback to EN for now)
  'mvp.hub.title': 'Omni All-In-One Hub',
  'mvp.hub.subtitle': 'Universal Entrance for InfoOne MVP & Awakening',
  'mvp.modules.report.title': 'Sustainability Report',
  'mvp.modules.report.desc': 'Automated data gathering and report generation compliant with GRI/SASB.',
  'mvp.modules.intelligence.title': 'Business Intelligence',
  'mvp.modules.intelligence.desc': 'Dr. Thoth monitoring 30+ benchmark sites. Market analysis and risk alerts.',
  'mvp.modules.avatar.title': 'Digital Twin',
  'mvp.modules.avatar.desc': 'Your "Second Self". Soul imprinting, prompt sanctuary, and agentic agency.',
  'mvp.modules.village.title': 'Benevolent Village',
  'mvp.modules.village.desc': 'ARPG gamified interface transforming ESG metrics into construction energy.',
  'mvp.modules.backend.title': 'Omni Backend',
  'mvp.modules.backend.desc': 'Deep monitoring, data management, and engineer system console.',
  'mvp.modules.personal.title': 'Personal Hub',
  'mvp.modules.personal.desc': 'Manage sovereign identity, personal storage, and North Star resonance.',
  'mvp.village.tasks': 'Tasks & Growth',
  'mvp.village.phase1': 'Phase 1: Sustainability Data Tracing [ISO-14064]',
  'mvp.village.phase2': 'Phase 2: Business Intelligence Hunting [Dr. Thoth]',
  'mvp.village.data': 'Sus-Data',
  'mvp.village.intelligence': 'Biz-Intel',
  'mvp.village.vault': 'Quantum Vault',
  'mvp.village.forest': 'Sus-Forest',
  'mvp.village.twin': 'Agentic Twin',
  'avatar.title': 'Digital Twin Center',
  'avatar.stats.title': 'Character Stats',
  'avatar.stats.strength': 'Strength',
  'avatar.stats.wisdom': 'Wisdom',
  'avatar.stats.agility': 'Agility',
  'avatar.stats.charisma': 'Charisma',
  'avatar.stats.endurance': 'Endurance',
  'avatar.skills.title': 'Skill System',
  'avatar.equipment.title': 'Equipment',
  'avatar.achievements.title': 'Achievements',
  'avatar.badges.title': 'Badges',
  'avatar.growth.title': 'Growth Track',
  'avatar.tabs.stats': 'Stats',
  'avatar.tabs.skills': 'Skills',
  'avatar.tabs.equipment': 'Equip',
  'avatar.tabs.achievements': 'Achi',
  'avatar.tabs.badges': 'Badges',
  'intel.title': 'Market Intel Center',
  'intel.status.scanning': 'Scanning...',
  'intel.status.active': 'Omni-Vision Active',
  'intel.sentinel.title': 'Sentinel Observation',
  'intel.impact_surface': 'Real-time ESG Impact Surface',
  'intel.global_flow': 'Global Intelligence',
  'intel.convert_task': 'CONVERT TO TASK',
  'intel.syncing': 'Gaia와 동기화 중...',
  'omni.dev.mapping.active': 'Omni 매핑 활성',
  'omni.dev.protocol.standby': '5T 프로토콜 대기',
  'omni.console.title': 'Omni 태그 콘솔',
  'omni.console.governance': '시스템 거버넌스 모드',
  'omni.console.spectrum': 'Omni 태그 스펙트럼',



  'mvp.metrics.overview': 'Metrics Overview',
  'mvp.metrics.data': 'Data Inventory',
  'mvp.metrics.audit': 'Compliance Audit',
  'mvp.metrics.report': 'Report Gen',
  'mvp.metrics.trace': 'Trace Chain',
  'mvp.metrics.origin': 'Source Origin',
  'mvp.metrics.rival': 'Competitor BM',
  'mvp.metrics.law': 'Regulatory',
  'mvp.metrics.awakening': 'The Awakening',
  'mvp.metrics.forge': 'Skill Forge',
  'mvp.metrics.agency': 'Agency Node',
  'mvp.metrics.omni': 'Omni Converter',
  'mvp.metrics.imprint': 'Imprinting',
  'mvp.metrics.contract': 'Policy Matrix',
  'mvp.metrics.audit_log': 'Activity Log',
  'mvp.metrics.badge': 'Soul Badge',
  'mvp.metrics.map': 'Village Map',
  'mvp.metrics.eco': 'Ecosystem',
  'mvp.metrics.energy': 'Energy Engine',
  'mvp.metrics.guild': 'Mission Guild',
  'mvp.metrics.entropy': 'Entropy Dash',
  'mvp.metrics.net': 'Agent Orchest',
  'mvp.metrics.review': 'Arch Review',
  'mvp.metrics.i18n': 'I18n Mapping',
  'mvp.nav.core': 'MVP Core',
  'mvp.nav.hub': 'Omni All-In-One Hub',
};





const translations: Record<Language, Record<TranslationKey, string>> = {
  'zh-TW': zhTwTranslations,
  'en-US': enUsTranslations,
  'ko-KR': koKrTranslations,
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string; // Typed t function
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh-TW');

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
