module.exports = {
  apps: [
    {
      name: 'esggo-core',
      cwd: '/var/www/esggo',
      script: 'pnpm',
      args: 'run start',
      env: { NODE_ENV: 'production', PORT: 3000, HOSTNAME: '127.0.0.1', NEXT_TELEMETRY_DISABLED: '1' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/error.log',
      out_file: 'logs/out.log',
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'omniagent-gateway',
      cwd: '/var/www/esggo/apps/gateway',
      script: 'omni-server.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: '8642' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/gateway-error.log',
      out_file: 'logs/gateway-out.log',
      merge_logs: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
    },
    {
      name: 'universal-translator',
      cwd: '/var/www/esggo/apps/universal-translator',
      script: 'server.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: '8788', STT_PORT: '8791' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/ut-error.log',
      out_file: 'logs/ut-out.log',
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 5,
    },
    {
      name: 'stt-whisper',
      cwd: '/var/www/esggo/apps/stt',
      script: 'server.py',
      interpreter: '/var/www/esggo/apps/stt/.venv/bin/python3',
      env: { NODE_ENV: 'production', STT_PORT: '8791', WHISPER_MODEL: 'base', WHISPER_DEVICE: 'cpu', WHISPER_COMPUTE: 'int8' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/stt-error.log',
      out_file: 'logs/stt-out.log',
      merge_logs: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
    },
    {
      name: 'deerflow',
      cwd: '/opt/deer-flow',
      script: '/var/www/esggo/vps-deploy/deerflow-watchdog.sh',
      interpreter: 'bash',
      env: { NODE_ENV: 'production' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/deerflow-error.log',
      out_file: 'logs/deerflow-out.log',
      merge_logs: true,
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 10,
    },
  ],
};
