allowBuilds:
  '@datadog/pprof': false
  '@firebase/util': false
  '@newrelic/fn-inspect': false
  '@newrelic/native-metrics': false
  better-sqlite3: true
  core-js: false
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@ai-sdk/openai@3.0.71'
  - '@ai-sdk/provider-utils@4.0.29'
