-- Create table for Newsletter Subscribers
CREATE TABLE IF NOT EXISTS esg_sunshine_newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    source TEXT DEFAULT 'homepage',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE esg_sunshine_newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public to insert (anyone can subscribe)
CREATE POLICY "Enable insert for everyone" ON esg_sunshine_newsletter_subscribers FOR INSERT WITH CHECK (true);

-- Create policy to allow only authenticated users (admins) to view
CREATE POLICY "Enable read for authenticated users only" ON esg_sunshine_newsletter_subscribers FOR SELECT TO authenticated USING (true);


-- Create table for Contact Messages
CREATE TABLE IF NOT EXISTS esg_sunshine_contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    job_title TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    company_name TEXT,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE esg_sunshine_contact_messages ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public to insert (anyone can contact)
CREATE POLICY "Enable insert for everyone" ON esg_sunshine_contact_messages FOR INSERT WITH CHECK (true);

-- Create policy to allow only authenticated users (admins) to view and update
CREATE POLICY "Enable all for authenticated users only" ON esg_sunshine_contact_messages FOR ALL TO authenticated USING (true);
