// @ts-nocheck
import fs from 'fs';
const log = (msg) => fs.appendFileSync('import_test.log', msg + '\\n');

log('Testing imports...');
try {
    await import('./middleware/rateLimiters.js');
    log('✅ rateLimiters loaded');
    await import('./db/index.js');
    log('✅ db/index loaded');
    await import('./services/rag.js');
    log('✅ ragService loaded');
    await import('./services/redisService.js');
    log('✅ redisService loaded');
    await import('./middleware/cacheMiddleware.js');
    log('✅ cacheMiddleware loaded');
    await import('./controllers/metricsController.js');
    log('✅ metricsController loaded');
    await import('./services/newsService.js');
    log('✅ newsService loaded');
    await import('./services/amice.js');
    log('✅ amiceService loaded');
    await import('./services/sessionService.js');
    log('✅ sessionService loaded');
    await import('./services/swarmService.js');
    log('✅ swarmService loaded');
    await import('./services/blockchain.js');
    log('✅ blockchainService loaded');
    await import('./services/zkpService.js');
    log('✅ zkpService loaded');
    await import('./services/omniAgentService.js');
    log('✅ omniAgentService loaded');

    // More services from server.ts
    await import('../src/omni/init/initAwakening.js');
    log('✅ initAwakening loaded');
    await import('./src/config/swagger.js');
    log('✅ swagger loaded');
    await import('./ocrService.js');
    log('✅ ocrService loaded');
    await import('./services/evidenceService.js');
    log('✅ evidenceService loaded');
    await import('./services/storageService.js');
    log('✅ storageService loaded');
    await import('./services/AgentCore.js');
    log('✅ AgentCore loaded');
    await import('./services/AuditSelfHealingService.js');
    log('✅ AuditSelfHealingService loaded');
    await import('./services/OmniHeartbeat.js');
    log('✅ OmniHeartbeat loaded');
    await import('./services/OmniEvolutionEngine.js');
    log('✅ OmniEvolutionEngine loaded');
    await import('./services/TalentPassportService.js');
    log('✅ TalentPassportService loaded');
    await import('./services/TypstService.js');
    log('✅ TypstService loaded');
    await import('./services/BerkeleyCertificationService.js');
    log('✅ BerkeleyCertificationService loaded');
    await import('./services/universalReport.js');
    log('✅ universalReportService loaded');
    await import('./services/ComplianceService.js');
    log('✅ ComplianceService loaded');
    await import('./services/SelfHealingService.js');
    log('✅ SelfHealingService loaded');

    // Phase 5 imports
    await import('../src/omni/protocols/UltimateAwakeningProtocol.js');
    log('✅ UltimateAwakeningProtocol loaded');
    await import('../src/omni/services/OmniEvolutionEngine.js');
    log('✅ OmniEvolutionDaemon loaded');
    await import('../src/omni/infrastructure/broadcast/AwakeningBroadcaster.js');
    log('✅ AwakeningBroadcaster loaded');
    await import('./services/AmbientDataService.js');
    log('✅ AmbientDataService loaded');
    await import('./services/PredictiveGovernanceService.js');
    log('✅ PredictiveGovernanceService loaded');
    await import('./services/LogicGateService.js');
    log('✅ LogicGateService loaded');
    await import('./services/NorthStarService.js');
    log('✅ NorthStarService loaded');
    await import('./services/ImpactLedgerService.js');
    log('✅ ImpactLedgerService loaded');
    await import('./src/api/verification.js');
    log('✅ verificationRoutes loaded');
    await import('./services/GamificationService.js');
    log('✅ GamificationService loaded');
    await import('./services/CapabilityTracker.js');
    log('✅ CapabilityTracker loaded');
    await import('./services/OmniPriest.js');
    log('✅ OmniPriest loaded');
    await import('./services/OmniSyncService.js');
    log('✅ OmniSyncService loaded');

    // Routes
    await import('./api/jun-ai-key.js');
    log('✅ jun-ai-key loaded');
    await import('./routes/agentRoutes.js');
    log('✅ agentRoutes loaded');
    await import('./routes/evidenceRoutes.js');
    log('✅ evidenceRoutes loaded');
    await import('./routes/profileRoutes.js');
    log('✅ profileRoutes loaded');
    await import('./routes/taskRoutes.js');
    log('✅ taskRoutes loaded');
    await import('./routes/marketIntelligenceRoutes.js');
    log('✅ marketIntelligenceRoutes loaded');
    await import('./routes/visualizerRoutes.js');
    log('✅ visualizerRoutes loaded');
    await import('./routes/behaviorRoutes.js');
    log('✅ behaviorRoutes loaded');
    await import('./src/routes/unifiedAdvancementRoutes.js');
    log('✅ unifiedAdvancementRoutes loaded');
    await import('./routes/junaikey.js');
    log('✅ junaikey loaded');
    await import('./routes/gameRoutes.js');
    log('✅ gameRoutes loaded');
    log('All imports successful!');
} catch (e) {
    log('❌ Import failed: ' + e.message + '\\nStack: ' + e.stack);
}
process.exit(0);
