// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { NextApiHandler, ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}

type ApiRouteConfig = {
  default: (req: any, res: any) => ReturnType<NextApiHandler>
  config?: {
    api?: {
      bodyParser?: boolean | { sizeLimit?: number | string }
      responseLimit?: string | number | boolean
      externalResolver?: boolean
    }
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    maxDuration?: number
  }
}


// Validate ../../app/4t-protocol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/4t-protocol">> = Specific
  const handler = {} as typeof import("../../app/4t-protocol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/4t-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/4t-verification">> = Specific
  const handler = {} as typeof import("../../app/4t-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/5t-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/5t-dashboard">> = Specific
  const handler = {} as typeof import("../../app/5t-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy">> = Specific
  const handler = {} as typeof import("../../app/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/omni-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/omni-table">> = Specific
  const handler = {} as typeof import("../../app/admin/omni-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advisors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advisors">> = Specific
  const handler = {} as typeof import("../../app/advisors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advisory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advisory">> = Specific
  const handler = {} as typeof import("../../app/advisory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/aha-moments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aha-moments">> = Specific
  const handler = {} as typeof import("../../app/aha-moments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-assistant">> = Specific
  const handler = {} as typeof import("../../app/ai-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai-platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-platform">> = Specific
  const handler = {} as typeof import("../../app/ai-platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/alliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alliance">> = Specific
  const handler = {} as typeof import("../../app/alliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../app/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-setup">> = Specific
  const handler = {} as typeof import("../../app/api-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apollo-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apollo-studio">> = Specific
  const handler = {} as typeof import("../../app/apollo-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-log">> = Specific
  const handler = {} as typeof import("../../app/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-verify">> = Specific
  const handler = {} as typeof import("../../app/audit-verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auto-processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auto-processing">> = Specific
  const handler = {} as typeof import("../../app/auto-processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/best-practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-practice">> = Specific
  const handler = {} as typeof import("../../app/best-practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blockchain-evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blockchain-evidence">> = Specific
  const handler = {} as typeof import("../../app/blockchain-evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/carbon-heatmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carbon-heatmap">> = Specific
  const handler = {} as typeof import("../../app/carbon-heatmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cbam-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cbam-calculator">> = Specific
  const handler = {} as typeof import("../../app/cbam-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance-check">> = Specific
  const handler = {} as typeof import("../../app/compliance-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/culture-transformation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/culture-transformation">> = Specific
  const handler = {} as typeof import("../../app/culture-transformation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer-journey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-journey">> = Specific
  const handler = {} as typeof import("../../app/customer-journey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/audit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/matrix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/matrix">> = Specific
  const handler = {} as typeof import("../../app/dashboard/matrix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/metrics/environmental/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metrics/environmental">> = Specific
  const handler = {} as typeof import("../../app/dashboard/metrics/environmental/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/metrics/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metrics/governance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/metrics/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metrics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/metrics/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metrics/social">> = Specific
  const handler = {} as typeof import("../../app/dashboard/metrics/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/premium/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/premium">> = Specific
  const handler = {} as typeof import("../../app/dashboard/premium/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/report-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/report-builder">> = Specific
  const handler = {} as typeof import("../../app/dashboard/report-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-connect">> = Specific
  const handler = {} as typeof import("../../app/data-connect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-sources">> = Specific
  const handler = {} as typeof import("../../app/data-sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-upload">> = Specific
  const handler = {} as typeof import("../../app/data-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug-platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug-platform">> = Specific
  const handler = {} as typeof import("../../app/debug-platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-library">> = Specific
  const handler = {} as typeof import("../../app/design-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/digital-twin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-twin">> = Specific
  const handler = {} as typeof import("../../app/digital-twin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/document-checklist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/document-checklist">> = Specific
  const handler = {} as typeof import("../../app/document-checklist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ecosystem-level/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecosystem-level">> = Specific
  const handler = {} as typeof import("../../app/ecosystem-level/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor">> = Specific
  const handler = {} as typeof import("../../app/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/efficiency-level/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/efficiency-level">> = Specific
  const handler = {} as typeof import("../../app/efficiency-level/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/environmental/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/environmental">> = Specific
  const handler = {} as typeof import("../../app/environmental/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/esggo-omnipencil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esggo-omnipencil">> = Specific
  const handler = {} as typeof import("../../app/esggo-omnipencil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/governance">> = Specific
  const handler = {} as typeof import("../../app/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gri-tracker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gri-tracker">> = Specific
  const handler = {} as typeof import("../../app/gri-tracker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gri">> = Specific
  const handler = {} as typeof import("../../app/gri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/health-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health-check">> = Specific
  const handler = {} as typeof import("../../app/health-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/integrity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrity">> = Specific
  const handler = {} as typeof import("../../app/integrity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence">> = Specific
  const handler = {} as typeof import("../../app/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investor-recognition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-recognition">> = Specific
  const handler = {} as typeof import("../../app/investor-recognition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investor-trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-trust">> = Specific
  const handler = {} as typeof import("../../app/investor-trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map">> = Specific
  const handler = {} as typeof import("../../app/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/materiality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materiality">> = Specific
  const handler = {} as typeof import("../../app/materiality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matrix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matrix">> = Specific
  const handler = {} as typeof import("../../app/matrix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/memory-shards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory-shards">> = Specific
  const handler = {} as typeof import("../../app/memory-shards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory">> = Specific
  const handler = {} as typeof import("../../app/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/oauth/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oauth/consent">> = Specific
  const handler = {} as typeof import("../../app/oauth/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-agent">> = Specific
  const handler = {} as typeof import("../../app/omni-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-components">> = Specific
  const handler = {} as typeof import("../../app/omni-components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-demo">> = Specific
  const handler = {} as typeof import("../../app/omni-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-factory">> = Specific
  const handler = {} as typeof import("../../app/omni-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-hub">> = Specific
  const handler = {} as typeof import("../../app/omni-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-key/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-key">> = Specific
  const handler = {} as typeof import("../../app/omni-key/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omni-notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omni-notes">> = Specific
  const handler = {} as typeof import("../../app/omni-notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omnispace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omnispace">> = Specific
  const handler = {} as typeof import("../../app/omnispace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/omnispace/sanctuary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omnispace/sanctuary">> = Specific
  const handler = {} as typeof import("../../app/omnispace/sanctuary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/one-click-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/one-click-report">> = Specific
  const handler = {} as typeof import("../../app/one-click-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform-versions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform-versions">> = Specific
  const handler = {} as typeof import("../../app/platform-versions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/proof-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proof-center">> = Specific
  const handler = {} as typeof import("../../app/proof-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/publish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/publish">> = Specific
  const handler = {} as typeof import("../../app/publish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/publish/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/publish/print">> = Specific
  const handler = {} as typeof import("../../app/publish/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reading-room/comparative-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reading-room/comparative-lab">> = Specific
  const handler = {} as typeof import("../../app/reading-room/comparative-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reading-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reading-room">> = Specific
  const handler = {} as typeof import("../../app/reading-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registry">> = Specific
  const handler = {} as typeof import("../../app/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/release-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/release-v2">> = Specific
  const handler = {} as typeof import("../../app/release-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/report-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-builder">> = Specific
  const handler = {} as typeof import("../../app/report-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/report-generation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-generation">> = Specific
  const handler = {} as typeof import("../../app/report-generation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../app/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/smart-esg/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/smart-esg">> = Specific
  const handler = {} as typeof import("../../app/smart-esg/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social">> = Specific
  const handler = {} as typeof import("../../app/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/soul/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/soul">> = Specific
  const handler = {} as typeof import("../../app/soul/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stakeholder-survey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stakeholder-survey">> = Specific
  const handler = {} as typeof import("../../app/stakeholder-survey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stakeholders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stakeholders">> = Specific
  const handler = {} as typeof import("../../app/stakeholders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/standards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/standards">> = Specific
  const handler = {} as typeof import("../../app/standards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../app/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/supply-chain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supply-chain">> = Specific
  const handler = {} as typeof import("../../app/supply-chain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sustain-write/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sustain-write">> = Specific
  const handler = {} as typeof import("../../app/sustain-write/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sustainable-culture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sustainable-culture">> = Specific
  const handler = {} as typeof import("../../app/sustainable-culture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/swarm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/swarm">> = Specific
  const handler = {} as typeof import("../../app/swarm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system-status">> = Specific
  const handler = {} as typeof import("../../app/system-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system-test">> = Specific
  const handler = {} as typeof import("../../app/system-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminal">> = Specific
  const handler = {} as typeof import("../../app/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-omni-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-omni-form">> = Specific
  const handler = {} as typeof import("../../app/test-omni-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/think-tank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/think-tank">> = Specific
  const handler = {} as typeof import("../../app/think-tank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user-passport/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user-passport">> = Specific
  const handler = {} as typeof import("../../app/user-passport/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/value-ladder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/value-ladder">> = Specific
  const handler = {} as typeof import("../../app/value-ladder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/value-levels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/value-levels">> = Specific
  const handler = {} as typeof import("../../app/value-levels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/value-path/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/value-path">> = Specific
  const handler = {} as typeof import("../../app/value-path/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vault">> = Specific
  const handler = {} as typeof import("../../app/vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/village/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/village">> = Specific
  const handler = {} as typeof import("../../app/village/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/walkthrough/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/walkthrough">> = Specific
  const handler = {} as typeof import("../../app/walkthrough/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/war-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/war-room">> = Specific
  const handler = {} as typeof import("../../app/war-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/webhooks">> = Specific
  const handler = {} as typeof import("../../app/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/zkp-blockchain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/zkp-blockchain">> = Specific
  const handler = {} as typeof import("../../app/zkp-blockchain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/5t/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/5t">> = Specific
  const handler = {} as typeof import("../../app/api/5t/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/artifacts/[artifactId]/promote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/artifacts/[artifactId]/promote">> = Specific
  const handler = {} as typeof import("../../app/api/agent/artifacts/[artifactId]/promote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/artifacts/[artifactId]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/artifacts/[artifactId]/review">> = Specific
  const handler = {} as typeof import("../../app/api/agent/artifacts/[artifactId]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/artifacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/artifacts">> = Specific
  const handler = {} as typeof import("../../app/api/agent/artifacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/executions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/executions">> = Specific
  const handler = {} as typeof import("../../app/api/agent/executions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/hermes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/hermes">> = Specific
  const handler = {} as typeof import("../../app/api/agent/hermes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/memory-shards/extract-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/memory-shards/extract-logs">> = Specific
  const handler = {} as typeof import("../../app/api/agent/memory-shards/extract-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/memory-shards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/memory-shards">> = Specific
  const handler = {} as typeof import("../../app/api/agent/memory-shards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent">> = Specific
  const handler = {} as typeof import("../../app/api/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/session">> = Specific
  const handler = {} as typeof import("../../app/api/agent/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/tasks/[taskId]/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/tasks/[taskId]/execute">> = Specific
  const handler = {} as typeof import("../../app/api/agent/tasks/[taskId]/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/agent/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/v3/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/v3/execute">> = Specific
  const handler = {} as typeof import("../../app/api/agent/v3/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/vision">> = Specific
  const handler = {} as typeof import("../../app/api/agent/vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/agentz0/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/agentz0">> = Specific
  const handler = {} as typeof import("../../app/api/agents/agentz0/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/best-practices/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/best-practices/recommend">> = Specific
  const handler = {} as typeof import("../../app/api/ai/best-practices/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/expand/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/expand">> = Specific
  const handler = {} as typeof import("../../app/api/ai/expand/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate">> = Specific
  const handler = {} as typeof import("../../app/api/ai/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/growth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/growth">> = Specific
  const handler = {} as typeof import("../../app/api/ai/growth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/list">> = Specific
  const handler = {} as typeof import("../../app/api/ai/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/search">> = Specific
  const handler = {} as typeof import("../../app/api/ai/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/stream">> = Specific
  const handler = {} as typeof import("../../app/api/ai/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/atomic/registry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/atomic/registry">> = Specific
  const handler = {} as typeof import("../../app/api/atomic/registry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit">> = Specific
  const handler = {} as typeof import("../../app/api/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth-providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth-providers">> = Specific
  const handler = {} as typeof import("../../app/api/auth-providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/google-signin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google-signin">> = Specific
  const handler = {} as typeof import("../../app/api/auth/google-signin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/best-practice/rag/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/best-practice/rag">> = Specific
  const handler = {} as typeof import("../../app/api/best-practice/rag/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bluecc/custom-fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bluecc/custom-fields">> = Specific
  const handler = {} as typeof import("../../app/api/bluecc/custom-fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bluecc/lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bluecc/lists">> = Specific
  const handler = {} as typeof import("../../app/api/bluecc/lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bluecc/records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bluecc/records">> = Specific
  const handler = {} as typeof import("../../app/api/bluecc/records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bluecc/workspaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bluecc/workspaces">> = Specific
  const handler = {} as typeof import("../../app/api/bluecc/workspaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cbam/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cbam">> = Specific
  const handler = {} as typeof import("../../app/api/cbam/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/compliance/gap-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/gap-analysis">> = Specific
  const handler = {} as typeof import("../../app/api/compliance/gap-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contracts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts">> = Specific
  const handler = {} as typeof import("../../app/api/contracts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/fetch-esg-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/fetch-esg-data">> = Specific
  const handler = {} as typeof import("../../app/api/cron/fetch-esg-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crypto/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crypto/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/crypto/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crypto/evm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crypto/evm">> = Specific
  const handler = {} as typeof import("../../app/api/crypto/evm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crypto/simulator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crypto/simulator">> = Specific
  const handler = {} as typeof import("../../app/api/crypto/simulator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/data/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/data/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/data/integrator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/integrator">> = Specific
  const handler = {} as typeof import("../../app/api/data/integrator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug-platform/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-platform">> = Specific
  const handler = {} as typeof import("../../app/api/debug-platform/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digital-twin/simulate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digital-twin/simulate">> = Specific
  const handler = {} as typeof import("../../app/api/digital-twin/simulate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/environmental/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/environmental/insights">> = Specific
  const handler = {} as typeof import("../../app/api/environmental/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/esg/crawl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/esg/crawl">> = Specific
  const handler = {} as typeof import("../../app/api/esg/crawl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/esg/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/esg/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/esg/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/evidence/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/stats">> = Specific
  const handler = {} as typeof import("../../app/api/evidence/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-report">> = Specific
  const handler = {} as typeof import("../../app/api/generate-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/genkit/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/genkit/analyze">> = Specific
  const handler = {} as typeof import("../../app/api/genkit/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/genkit/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/genkit/generate">> = Specific
  const handler = {} as typeof import("../../app/api/genkit/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/governance/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governance/insights">> = Specific
  const handler = {} as typeof import("../../app/api/governance/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/governance/resonance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governance/resonance">> = Specific
  const handler = {} as typeof import("../../app/api/governance/resonance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/graphql/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graphql">> = Specific
  const handler = {} as typeof import("../../app/api/graphql/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gri/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gri">> = Specific
  const handler = {} as typeof import("../../app/api/gri/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hub/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hub">> = Specific
  const handler = {} as typeof import("../../app/api/hub/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hub/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hub/search">> = Specific
  const handler = {} as typeof import("../../app/api/hub/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hub/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hub/stream">> = Specific
  const handler = {} as typeof import("../../app/api/hub/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hub/ws/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hub/ws">> = Specific
  const handler = {} as typeof import("../../app/api/hub/ws/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrity/zkp-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrity/zkp-generate">> = Specific
  const handler = {} as typeof import("../../app/api/integrity/zkp-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/intelligence/health-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence/health-check">> = Specific
  const handler = {} as typeof import("../../app/api/intelligence/health-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence">> = Specific
  const handler = {} as typeof import("../../app/api/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/internal/consolidate-memories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/consolidate-memories">> = Specific
  const handler = {} as typeof import("../../app/api/internal/consolidate-memories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matrix">> = Specific
  const handler = {} as typeof import("../../app/api/matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory">> = Specific
  const handler = {} as typeof import("../../app/api/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/search">> = Specific
  const handler = {} as typeof import("../../app/api/memory/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/vectorize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/vectorize">> = Specific
  const handler = {} as typeof import("../../app/api/memory/vectorize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/metrics/[module]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/[module]">> = Specific
  const handler = {} as typeof import("../../app/api/metrics/[module]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/metrics/editor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/editor">> = Specific
  const handler = {} as typeof import("../../app/api/metrics/editor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/metrics/esg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/esg">> = Specific
  const handler = {} as typeof import("../../app/api/metrics/esg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/metrics/heal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/heal">> = Specific
  const handler = {} as typeof import("../../app/api/metrics/heal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nexus/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nexus/agent">> = Specific
  const handler = {} as typeof import("../../app/api/nexus/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes">> = Specific
  const handler = {} as typeof import("../../app/api/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oa/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oa/google/callback">> = Specific
  const handler = {} as typeof import("../../app/api/oa/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oa/google/oauth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oa/google/oauth">> = Specific
  const handler = {} as typeof import("../../app/api/oa/google/oauth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oa/google/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oa/google/status">> = Specific
  const handler = {} as typeof import("../../app/api/oa/google/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/consent/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/consent/approve">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/consent/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/alchemy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/alchemy">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/alchemy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/command">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/extract-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/extract-metrics">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/extract-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/hitl-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/hitl-review">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/hitl-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/scan-vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/scan-vision">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/scan-vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/schedule">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/stream/events/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/stream/events/stats">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/stream/events/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/stream">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/telemetry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/telemetry">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/telemetry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent-api/vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent-api/vision">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent-api/vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/celestial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/celestial">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/celestial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/chat">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/image">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/ingest">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/notes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/notes">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/rag/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/rag">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/rag/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-agent/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-agent/voice">> = Specific
  const handler = {} as typeof import("../../app/api/omni-agent/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-avatar/heal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-avatar/heal">> = Specific
  const handler = {} as typeof import("../../app/api/omni-avatar/heal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-blue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-blue">> = Specific
  const handler = {} as typeof import("../../app/api/omni-blue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-command">> = Specific
  const handler = {} as typeof import("../../app/api/omni-command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-components/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-components">> = Specific
  const handler = {} as typeof import("../../app/api/omni-components/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-gateway/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-gateway">> = Specific
  const handler = {} as typeof import("../../app/api/omni-gateway/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-jules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-jules">> = Specific
  const handler = {} as typeof import("../../app/api/omni-jules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-key/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-key/create">> = Specific
  const handler = {} as typeof import("../../app/api/omni-key/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-key/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-key/list">> = Specific
  const handler = {} as typeof import("../../app/api/omni-key/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-key/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-key/revoke">> = Specific
  const handler = {} as typeof import("../../app/api/omni-key/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-key/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-key/verify">> = Specific
  const handler = {} as typeof import("../../app/api/omni-key/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-matrix">> = Specific
  const handler = {} as typeof import("../../app/api/omni-matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-memory">> = Specific
  const handler = {} as typeof import("../../app/api/omni-memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-notes">> = Specific
  const handler = {} as typeof import("../../app/api/omni-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-notes/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-notes/sync">> = Specific
  const handler = {} as typeof import("../../app/api/omni-notes/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-sync">> = Specific
  const handler = {} as typeof import("../../app/api/omni-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-table">> = Specific
  const handler = {} as typeof import("../../app/api/omni-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-table/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-table/status">> = Specific
  const handler = {} as typeof import("../../app/api/omni-table/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omni-workflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omni-workflows">> = Specific
  const handler = {} as typeof import("../../app/api/omni-workflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omniblue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omniblue">> = Specific
  const handler = {} as typeof import("../../app/api/omniblue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omnicore/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omnicore/lookup">> = Specific
  const handler = {} as typeof import("../../app/api/omnicore/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omnicore/scrape-esg-web/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omnicore/scrape-esg-web">> = Specific
  const handler = {} as typeof import("../../app/api/omnicore/scrape-esg-web/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omnicore/seal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omnicore/seal">> = Specific
  const handler = {} as typeof import("../../app/api/omnicore/seal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omnicore/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omnicore/verify">> = Specific
  const handler = {} as typeof import("../../app/api/omnicore/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/omnispace/sse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omnispace/sse">> = Specific
  const handler = {} as typeof import("../../app/api/omnispace/sse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/platform/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/versions">> = Specific
  const handler = {} as typeof import("../../app/api/platform/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proof/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proof/resend">> = Specific
  const handler = {} as typeof import("../../app/api/proof/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public-data/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public-data/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/public-data/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/qpi/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qpi/score">> = Specific
  const handler = {} as typeof import("../../app/api/qpi/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/rag/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/query">> = Specific
  const handler = {} as typeof import("../../app/api/rag/query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/search">> = Specific
  const handler = {} as typeof import("../../app/api/rag/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/upload">> = Specific
  const handler = {} as typeof import("../../app/api/rag/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reading-room/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-room/documents">> = Specific
  const handler = {} as typeof import("../../app/api/reading-room/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reading-room/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-room/stats">> = Specific
  const handler = {} as typeof import("../../app/api/reading-room/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scraper/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scraper">> = Specific
  const handler = {} as typeof import("../../app/api/scraper/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/slack/command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slack/command">> = Specific
  const handler = {} as typeof import("../../app/api/slack/command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/slack/push5t/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slack/push5t">> = Specific
  const handler = {} as typeof import("../../app/api/slack/push5t/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/slack/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slack/status">> = Specific
  const handler = {} as typeof import("../../app/api/slack/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/insights">> = Specific
  const handler = {} as typeof import("../../app/api/social/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sustain-write/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sustain-write/generate">> = Specific
  const handler = {} as typeof import("../../app/api/sustain-write/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sustain-write/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sustain-write">> = Specific
  const handler = {} as typeof import("../../app/api/sustain-write/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/swarm/trigger/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/swarm/trigger">> = Specific
  const handler = {} as typeof import("../../app/api/swarm/trigger/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/system/autonomy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/autonomy">> = Specific
  const handler = {} as typeof import("../../app/api/system/autonomy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/system/heal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/heal">> = Specific
  const handler = {} as typeof import("../../app/api/system/heal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/system/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/health">> = Specific
  const handler = {} as typeof import("../../app/api/system/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/system/memory-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/memory-health">> = Specific
  const handler = {} as typeof import("../../app/api/system/memory-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/telemetry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telemetry">> = Specific
  const handler = {} as typeof import("../../app/api/telemetry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/terminal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terminal">> = Specific
  const handler = {} as typeof import("../../app/api/terminal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trpc/[trpc]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trpc/[trpc]">> = Specific
  const handler = {} as typeof import("../../app/api/trpc/[trpc]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/activity-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/activity-log">> = Specific
  const handler = {} as typeof import("../../app/api/user/activity-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/preferences">> = Specific
  const handler = {} as typeof import("../../app/api/user/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/data/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/data/ingest">> = Specific
  const handler = {} as typeof import("../../app/api/v1/data/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/health">> = Specific
  const handler = {} as typeof import("../../app/api/v1/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/metrics">> = Specific
  const handler = {} as typeof import("../../app/api/v1/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault-omni/engrave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault-omni/engrave">> = Specific
  const handler = {} as typeof import("../../app/api/vault-omni/engrave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault-omni/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault-omni/verify">> = Specific
  const handler = {} as typeof import("../../app/api/vault-omni/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/audit">> = Specific
  const handler = {} as typeof import("../../app/api/vault/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/indicators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/indicators">> = Specific
  const handler = {} as typeof import("../../app/api/vault/indicators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/list">> = Specific
  const handler = {} as typeof import("../../app/api/vault/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/omni/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/omni">> = Specific
  const handler = {} as typeof import("../../app/api/vault/omni/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/read">> = Specific
  const handler = {} as typeof import("../../app/api/vault/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/roundtrip-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/roundtrip-test">> = Specific
  const handler = {} as typeof import("../../app/api/vault/roundtrip-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault">> = Specific
  const handler = {} as typeof import("../../app/api/vault/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/seal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/seal">> = Specific
  const handler = {} as typeof import("../../app/api/vault/seal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/stats">> = Specific
  const handler = {} as typeof import("../../app/api/vault/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/verify">> = Specific
  const handler = {} as typeof import("../../app/api/vault/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vault/write/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/write">> = Specific
  const handler = {} as typeof import("../../app/api/vault/write/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/ncbdb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/ncbdb">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/ncbdb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/ncbdb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/ncbdb">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/ncbdb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/zkp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/zkp">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/zkp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zkp/seal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zkp/seal">> = Specific
  const handler = {} as typeof import("../../app/api/zkp/seal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zkp/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zkp/store">> = Specific
  const handler = {} as typeof import("../../app/api/zkp/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}



// Validate ../../pages/api/omni-core/[id].ts
{
  type __IsExpected<Specific extends ApiRouteConfig> = Specific
  const handler = {} as typeof import("../../pages/api/omni-core/[id].js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../pages/api/swarm/ws.ts
{
  type __IsExpected<Specific extends ApiRouteConfig> = Specific
  const handler = {} as typeof import("../../pages/api/swarm/ws.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-sources/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/data-sources">> = Specific
  const handler = {} as typeof import("../../app/data-sources/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
