version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: esggo-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - TZ=Asia/Taipei
    networks:
      - esggo-net

networks:
  esggo-net:
    external: true
    name: esggo-net
