var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/omni-memory/route.js")
R.c("server/chunks/[root-of-the-server]__0arb6gz._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0cb966i.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__1yt1ie3._.js")
R.c("server/chunks/node_modules_1ssowgd._.js")
R.c("server/chunks/[root-of-the-server]__0y6567a._.js")
R.c("server/chunks/node_modules_15ff9zg._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/node_modules_zod_v3_1h7_2ut._.js")
R.c("server/chunks/_next-internal_server_app_api_omni-memory_route_actions_20j0fbg.js")
R.m(972557)
module.exports=R.m(972557).exports
