import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface NoteData {
  id: string;
  contextId: string;
  content: string;
  tags: string[];
  updatedAt: number;
  // 🔄 OmniCircle - 日誌關聯功能
  linkedLogIds?: string[];           // 關聯的日誌 ID 列表
  autoGenerated?: boolean;           // 是否自動產生
  investigationStatus?: 'open' | 'investigating' | 'resolved'; // 調查狀態

  // 🏛️ OmniKnowledgeBase - 知識資產整合
  isKnowledgeAsset?: boolean;        // 標記為知識資產
  knowledgeId?: string;              // 對應知識庫 ID
  qualityScore?: number;             // 品質評分 (0-100)
  knowledgeCategory?: string;        // 知識類別
}

interface NoteStore {
  notes: Record<string, NoteData>; // Key: contextId
  saveNote: (contextId: string, content: string, metadata?: Partial<NoteData>) => void;
  getNote: (contextId: string) => NoteData | undefined;
  deleteNote: (contextId: string) => void;
  updateNoteMetadata: (contextId: string, metadata: Partial<NoteData>) => void;
  addLogToNote: (contextId: string, logId: string) => void;
}

export const useNoteSystem = create<NoteStore>()(
  persist(
    (set, get) => ({
      notes: {},

      saveNote: (contextId, content, metadata) =>
        set(state => ({
          notes: {
            ...state.notes,
            [contextId]: {
              id: state.notes[contextId]?.id || crypto.randomUUID(),
              contextId,
              content,
              tags: metadata?.tags || state.notes[contextId]?.tags || [],
              updatedAt: Date.now(),
              // 🔄 OmniCircle - 日誌關聯功能
              linkedLogIds: metadata?.linkedLogIds || state.notes[contextId]?.linkedLogIds || [],
              autoGenerated: metadata?.autoGenerated !== undefined ? metadata.autoGenerated : state.notes[contextId]?.autoGenerated,
              investigationStatus: metadata?.investigationStatus || state.notes[contextId]?.investigationStatus,
              // 🏛️ OmniKnowledgeBase - 知識資產整合
              isKnowledgeAsset: metadata?.isKnowledgeAsset !== undefined ? metadata.isKnowledgeAsset : state.notes[contextId]?.isKnowledgeAsset,
              knowledgeId: metadata?.knowledgeId || state.notes[contextId]?.knowledgeId,
              qualityScore: metadata?.qualityScore !== undefined ? metadata.qualityScore : state.notes[contextId]?.qualityScore,
              knowledgeCategory: metadata?.knowledgeCategory || state.notes[contextId]?.knowledgeCategory,
            },
          },
        })),

      getNote: contextId => get().notes[contextId],

      deleteNote: contextId =>
        set(state => {
          const newNotes = { ...state.notes };
          delete newNotes[contextId];
          return { notes: newNotes };
        }),

      updateNoteMetadata: (contextId, metadata) => {
        const note = get().notes[contextId];
        if (!note) return;
        get().saveNote(contextId, note.content, metadata);
      },

      addLogToNote: (contextId, logId) => {
        const note = get().notes[contextId];
        if (!note) return;
        const linkedLogIds = Array.from(new Set([...(note.linkedLogIds || []), logId]));
        get().saveNote(contextId, note.content, { linkedLogIds });
      },
    }),
    { name: 'jun-ai-key-notes' }
  )
);
