platform :ios, '14.0'

target 'esggo' do
  pod 'NewRelic', '~> 7.7.6'
  pod 'React', path: '../node_modules/react'
  pod 'React-Core', path: '../node_modules/react'
  pod 'React-Native', path: '../node_modules/react-native'
  pod 'Firebase', '~> 10.0'
  pod 'Firebase/Analytics', '~> 10.0'
  pod 'Firebase/Crashlytics', '~> 10.0'
end