server {
    listen 80;
    server_name journey.ftgtours.esggo.co;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name journey.ftgtours.esggo.co;
    root /var/www/ftg-journey-web;
    index index.html;
    ssl_certificate /etc/letsencrypt/live/journey-api.ftgtours.esggo.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/journey-api.ftgtours.esggo.co/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { try_files $uri $uri/ /index.html; }
}
