extend type AuditLog {
  """
  ✨ Implicit foreign key field based on `AuditLog`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "AuditLog.user", purpose: IMPLICIT_REF_FIELD)
}
extend type EsgRecord {
  """
  ✨ Implicit foreign key field based on `EsgRecord`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "EsgRecord.user", purpose: IMPLICIT_REF_FIELD)
}
