extend type Query {
  """
  ✨ Look up a single `AuditLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  auditLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AuditLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AuditLog_FirstRow
  ): AuditLog @fdc_generated(from: "AuditLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DashboardMetric` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dashboardMetric(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DashboardMetric_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DashboardMetric_FirstRow
  ): DashboardMetric @fdc_generated(from: "DashboardMetric", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Evidence` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  evidence(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Evidence_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Evidence_FirstRow
  ): Evidence @fdc_generated(from: "Evidence", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `OcrReviewItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  ocrReviewItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OcrReviewItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OcrReviewItem_FirstRow
  ): OcrReviewItem @fdc_generated(from: "OcrReviewItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `AuditLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  auditLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: AuditLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AuditLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AuditLog_Having
  ): [AuditLog!]! @fdc_generated(from: "AuditLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DashboardMetric` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dashboardMetrics(
    """
    Filter condition to narrow down the query results.
    """
    where: DashboardMetric_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DashboardMetric_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DashboardMetric_Having
  ): [DashboardMetric!]! @fdc_generated(from: "DashboardMetric", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Evidence` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  evidences(
    """
    Filter condition to narrow down the query results.
    """
    where: Evidence_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Evidence_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Evidence_Having
  ): [Evidence!]! @fdc_generated(from: "Evidence", purpose: QUERY_MULTIPLE)
  """
  ✨ List `OcrReviewItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  ocrReviewItems(
    """
    Filter condition to narrow down the query results.
    """
    where: OcrReviewItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OcrReviewItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OcrReviewItem_Having
  ): [OcrReviewItem!]! @fdc_generated(from: "OcrReviewItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
