extend type AuditLog {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "AuditLog", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `AuditLog` table.
  """
  _count: Int! @fdc_generated(from: "AuditLog.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `nodeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nodeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.nodeId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `proof` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  proof_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.proof", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `AuditLog` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "AuditLog.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `AuditLog` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "AuditLog.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "AuditLog.id", purpose: ENTITY_ID)
}
extend type DashboardMetric {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "DashboardMetric", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `DashboardMetric` table.
  """
  _count: Int! @fdc_generated(from: "DashboardMetric.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `percentageChange` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  percentageChange_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.percentageChange", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `trend` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trend_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.trend", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `unit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  unit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.unit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DashboardMetric` table where the `value` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  value_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DashboardMetric.value", purpose: QUERY_COUNT)
  """
  ✨ Sum the `percentageChange` field in the `DashboardMetric` table.
  """
  percentageChange_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "DashboardMetric.percentageChange", purpose: QUERY_SUM)
  """
  ✨ Sum the `value` field in the `DashboardMetric` table.
  """
  value_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "DashboardMetric.value", purpose: QUERY_SUM)
  """
  ✨ Average the `percentageChange` field in the `DashboardMetric` table.
  """
  percentageChange_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "DashboardMetric.percentageChange", purpose: QUERY_AVG)
  """
  ✨ Average the `value` field in the `DashboardMetric` table.
  """
  value_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "DashboardMetric.value", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `percentageChange` field in the `DashboardMetric` table.
  """
  percentageChange_min: Float @fdc_generated(from: "DashboardMetric.percentageChange", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timestamp` field in the `DashboardMetric` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "DashboardMetric.timestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `value` field in the `DashboardMetric` table.
  """
  value_min: Float @fdc_generated(from: "DashboardMetric.value", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `percentageChange` field in the `DashboardMetric` table.
  """
  percentageChange_max: Float @fdc_generated(from: "DashboardMetric.percentageChange", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timestamp` field in the `DashboardMetric` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "DashboardMetric.timestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `value` field in the `DashboardMetric` table.
  """
  value_max: Float @fdc_generated(from: "DashboardMetric.value", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "DashboardMetric.id", purpose: ENTITY_ID)
}
extend type Evidence {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Evidence", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Evidence` table.
  """
  _count: Int! @fdc_generated(from: "Evidence.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `confidenceScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  confidenceScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.confidenceScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `source` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  source_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.source", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Evidence` table where the `verified` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  verified_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Evidence.verified", purpose: QUERY_COUNT)
  """
  ✨ Sum the `confidenceScore` field in the `Evidence` table.
  """
  confidenceScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Evidence.confidenceScore", purpose: QUERY_SUM)
  """
  ✨ Average the `confidenceScore` field in the `Evidence` table.
  """
  confidenceScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Evidence.confidenceScore", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `confidenceScore` field in the `Evidence` table.
  """
  confidenceScore_min: Float @fdc_generated(from: "Evidence.confidenceScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timestamp` field in the `Evidence` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "Evidence.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `confidenceScore` field in the `Evidence` table.
  """
  confidenceScore_max: Float @fdc_generated(from: "Evidence.confidenceScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timestamp` field in the `Evidence` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "Evidence.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Evidence.id", purpose: ENTITY_ID)
}
extend type OcrReviewItem {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "OcrReviewItem", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table.
  """
  _count: Int! @fdc_generated(from: "OcrReviewItem.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `confidenceScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  confidenceScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.confidenceScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `extractedValue` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  extractedValue_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.extractedValue", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `fieldLabel` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fieldLabel_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.fieldLabel", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `originalSource` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  originalSource_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.originalSource", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `unit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  unit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.unit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OcrReviewItem` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OcrReviewItem.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `confidenceScore` field in the `OcrReviewItem` table.
  """
  confidenceScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OcrReviewItem.confidenceScore", purpose: QUERY_SUM)
  """
  ✨ Average the `confidenceScore` field in the `OcrReviewItem` table.
  """
  confidenceScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OcrReviewItem.confidenceScore", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `confidenceScore` field in the `OcrReviewItem` table.
  """
  confidenceScore_min: Float @fdc_generated(from: "OcrReviewItem.confidenceScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timestamp` field in the `OcrReviewItem` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "OcrReviewItem.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `confidenceScore` field in the `OcrReviewItem` table.
  """
  confidenceScore_max: Float @fdc_generated(from: "OcrReviewItem.confidenceScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timestamp` field in the `OcrReviewItem` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "OcrReviewItem.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "OcrReviewItem.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `DashboardMetric` objects in a one-to-many relationship (where `DashboardMetric`.`user` is this object).
  """
  dashboardMetrics_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: DashboardMetric_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DashboardMetric_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DashboardMetric_Having
  ): [DashboardMetric!]! @fdc_generated(from: "DashboardMetric.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Evidence` objects in a one-to-many relationship (where `Evidence`.`user` is this object).
  """
  evidences_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Evidence_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Evidence_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Evidence_Having
  ): [Evidence!]! @fdc_generated(from: "Evidence.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `OcrReviewItem` objects in a one-to-many relationship (where `OcrReviewItem`.`user` is this object).
  """
  ocrReviewItems_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: OcrReviewItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OcrReviewItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OcrReviewItem_Having
  ): [OcrReviewItem!]! @fdc_generated(from: "OcrReviewItem.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
