var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/audit-log/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00uex50._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0yt2b00.js")
R.c("server/chunks/ssr/[root-of-the-server]__087nj0h._.js")
R.c("server/chunks/ssr/node_modules_0c4h-pv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15ohnpm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/app_global-error_tsx_113y3za._.js")
R.c("server/chunks/ssr/_next-internal_server_app_audit-log_page_actions_16pwmyz.js")
R.m(398514)
module.exports=R.m(398514).exports
