import requests
import json
import re

with open('.env.local', encoding='utf-8-sig') as f:
    env = f.read()

url = re.search(r'^NEXT_PUBLIC_SUPABASE_URL=(.*)$', env, re.M).group(1)
anon_key = re.search(r'^NEXT_PUBLIC_SUPABASE_ANON_KEY=(.*)$', env, re.M).group(1)
service_key = re.search(r'^SUPABASE_SERVICE_ROLE_KEY=(.*)$', env, re.M).group(1)

rest = url.rstrip('/') + '/rest/v1'
headers = {
    'apikey': service_key,
    'Authorization': f'Bearer {service_key}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

docs = [
  {"id":"std-gri-2021","title":"GRI 2021 Universal Standards","description":"GRI 通用準則為所有組織提供關於一般揭露（組織資訊、活動、治理等）的基礎框架，是 GRI 標準的核心基礎。","category":"standard","file_url":"https://www.globalreporting.org/standards/media/1001/gri-101-biodiversity-2024.pdf","gri_reference":"GRI 2","esg_category":"Governance","tags":["GRI","Universal Standards","Governance","Organization"],"source":"https://www.globalreporting.org/standards/","published_date":"2023-01-01"},
  {"id":"std-gri-305","title":"GRI 305: Emissions 2016","description":"規範組織對溫室氣體排放的揭露要求，涵蓋直接排放（範疇一）、能源間接排放（範疇二）及其他間接排放（範疇三）。","category":"standard","file_url":"https://www.globalreporting.org/standards/media/1012/gri-305-emissions-2016.pdf","gri_reference":"GRI 305","esg_category":"Environmental","tags":["GRI","Emissions","Scope 1","Scope 2","Scope 3","GHG"],"source":"https://www.globalreporting.org/standards/media/1012/gri-305-emissions-2016.pdf","published_date":"2016-07-01"},
  {"id":"std-gri-302","title":"GRI 302: Energy 2016","description":"規範組織對能源消耗、能源強度及再生能源使用情況的揭露要求。","category":"standard","file_url":"https://www.globalreporting.org/standards/media/1009/gri-302-energy-2016.pdf","gri_reference":"GRI 302","esg_category":"Environmental","tags":["GRI","Energy","Renewable Energy","Consumption"],"source":"https://www.globalreporting.org/standards/media/1009/gri-302-energy-2016.pdf","published_date":"2016-07-01"},
  {"id":"std-tcfd","title":"TCFD Recommendations","description":"TCFD 建議企業依據「治理」、「策略」、「風險管理」及「指標與目標」四大支柱揭露氣候相關財務風險與機會。","category":"standard","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["TCFD","Climate","Risk","Disclosure"],"source":"https://www.fsb-tcfd.org/","published_date":"2017-06-29"},
  {"id":"std-issb-s1","title":"IFRS S1 General Requirements for Disclosure of Sustainability-related Financial Information","description":"IFRS S1 規定企業應揭露對其在短、中、長期產生重大影響之永續相關風險和機會的相關資訊。","category":"standard","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["ISSB","IFRS S1","Sustainability","Financial Disclosure"],"source":"https://www.ifrs.org/issued-standards/ifrs-sustainability-disclosure-standards/","published_date":"2024-01-01"},
  {"id":"std-issb-s2","title":"IFRS S2 Climate-related Disclosures","description":"IFRS S2 專注於氣候相關風險和機會的揭露，建立在 TCFD 框架之上，並要求額外的量化指標揭露。","category":"standard","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["ISSB","IFRS S2","Climate","GHG","Emissions"],"source":"https://www.ifrs.org/issued-standards/ifrs-sustainability-disclosure-standards/ifrs-s2-climate-related-disclosures/","published_date":"2024-01-01"},
  {"id":"std-iso-14064","title":"ISO 14064-1:2018 Greenhouse gases — Specification with guidance for quantification and reporting","description":"提供組織層級溫室氣體排放和移除的量化及報告規範，是溫室氣體盤查最重要的國際標準。","category":"standard","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["ISO","GHG","Inventory","Verification"],"source":"https://www.iso.org/standard/66453.html","published_date":"2018-12-01"},
  {"id":"std-iso-14001","title":"ISO 14001:2015 Environmental management systems","description":"ISO 14001 規定環境管理系統的要求，協助組織提升環境績效、履行合規義務及達成環境目標。","category":"standard","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["ISO","EMS","Environmental Management"],"source":"https://www.iso.org/iso-14001-environmental-management.html","published_date":"2015-09-15"},
  {"id":"std-tw-fsc","title":"金管會上市（櫃）公司永續發展路徑圖","description":"金管會規定台灣上市上櫃公司分階段提升 ESG 揭露標準，要求依 GRI 準則編製永續報告書，並逐步導入 IFRS S1/S2。","category":"regulation","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["台灣法規","金管會","ESG","永續報告"],"source":"https://www.fsc.gov.tw","published_date":"2023-01-01"},
  {"id":"reg-eu-csrd","title":"Corporate Sustainability Reporting Directive / European Sustainability Reporting Standards","description":"CSRD 是歐盟最新的永續報告法規，要求企業依 ESRS 揭露 ESG 資訊，引入「雙重重大性」原則。","category":"regulation","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["EU","CSRD","ESRS","Double Materiality"],"source":"https://finance.ec.europa.eu/capital-markets-union-and-financial-markets/company-reporting-and-auditing/company-reporting/corporate-sustainability-reporting_en","published_date":"2024-01-01"},
  {"id":"reg-eu-cbam","title":"EU 2023/956: CBAM Implementing Regulation","description":"CBAM 對進入歐盟的高碳商品（鋼鐵、鋁、水泥、化肥、電力、氫氣）課徵碳關稅，台灣出口商須建立碳足跡追蹤與申報機制。","category":"regulation","file_url":"https://eur-lex.europa.eu/eli/reg/2023/956","gri_reference":None,"esg_category":"Environmental","tags":["EU","CBAM","Carbon Border","Regulation"],"source":"https://eur-lex.europa.eu/eli/reg/2023/956","published_date":"2023-05-16"},
  {"id":"rep-tw-carbon-fee","title":"氣候變遷因應法：碳費徵收辦法草案","description":"行政院環境部公告碳費徵收對象與計算方式。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["台灣","Carbon Fee","氣候變遷"],"source":"https://enews.moenv.gov.tw/","published_date":"2024-04-29"},
  {"id":"std-gri-biodiversity-2024","title":"GRI 101: Biodiversity 2024","description":"Major update to biodiversity reporting standards.","category":"standard","file_url":"https://www.globalreporting.org/standards/media/1001/gri-101-biodiversity-2024.pdf","gri_reference":"GRI 101","esg_category":"Environmental","tags":["GRI","Biodiversity","Nature"],"source":"https://www.globalreporting.org/","published_date":"2024-01-25"},
  {"id":"std-sasb-tech","title":"SASB Technology & Communications — Software & IT Services","description":"針對軟體與 IT 服務產業的永續會計標準，重點揭露能源管理、資安隱私、勞工實踐及創新管理等議題。","category":"standard","file_url":None,"gri_reference":None,"esg_category":"Social","tags":["SASB","Technology","Software","IT Services"],"source":"https://sasb.org/standards/technology-communications/","published_date":"2018-10-04"},
  {"id":"yearbook-tw-2015","title":"台灣企業永續發展年鑑 2015","description":"收錄台灣上市櫃公司 2015 年度 ESG 揭露成果，包含首批主動揭露 CSR 報告之中大型企業實績。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["台灣","年鑑","永續報告","CSR","TWSE"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2015-12-31"},
  {"id":"yearbook-tw-2016","title":"台灣企業永續發展年鑑 2016","description":"收錄台灣上市櫃公司 2016 年度 ESG 揭露成果，建置首批自願性 CSR 報告企業清冊，涵蓋電子、金融、製造業。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["台灣","年鑑","永續報告","CSR","TWSE"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2016-12-31"},
  {"id":"yearbook-tw-2017","title":"台灣企業永續發展年鑑 2017","description":"收錄台灣上市櫃公司 2017 年度 ESG 揭露成果，首度出現 TCFD 先行揭露指標，並納入 CDP 問卷回覆分析。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["台灣","年鑑","永續報告","CSR","TCFD","CDP"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2017-12-31"},
  {"id":"yearbook-tw-2018","title":"台灣企業永續發展年鑑 2018","description":"收錄台灣上市櫃公司 2018 年度 ESG 揭露成果，首度針對 SASB 產業別指標進行對照分析，新增 S 與 G 揭露強化指標。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Social","tags":["台灣","年鑑","永續報告","CSR","SASB"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2018-12-31"},
  {"id":"yearbook-tw-2019","title":"台灣企業永續發展年鑑 2019","description":"收錄台灣上市櫃公司 2019 年度 ESG 揭露成果，納入 GRI 準則全面轉換檢查，並初次彙整供應鏈減碳承諾與再生能源使用情形。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["台灣","年鑑","永續報告","CSR","GRI","再生能源"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2019-12-31"},
  {"id":"yearbook-tw-2020","title":"台灣企業永續發展年鑑 2020","description":"收錄台灣上市櫃公司 2020 年度 ESG 揭露成果，因應疫情強化 S 軸（員工健康、供應鏈韌性）揭露，並加入科學基礎減量目標 (SBTi) 追蹤。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Social","tags":["台灣","年鑑","永續報告","CSR","SBTi","疫情"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2020-12-31"},
  {"id":"yearbook-tw-2021","title":"台灣企業永續發展年鑑 2021","description":"收錄台灣上市櫃公司 2021 年度 ESG 揭露成果，首度完整配合 GRI 2021 通用準則編撰，並導入碳定價與氣候情境分析揭露。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["台灣","年鑑","永續報告","CSR","GRI 2021","氣候情境"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2021-12-31"},
  {"id":"yearbook-tw-2022","title":"台灣企業永續發展年鑑 2022","description":"收錄台灣上市櫃公司 2022 年度 ESG 揭露成果，納入 CBAM 概念揭露引導、Scope 3 揭露占比提升，並交叉比對 MSCI / CDP 評等結果。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["台灣","年鑑","永續報告","CSR","CBAM","Scope 3","MSCI","CDP"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2022-12-31"},
  {"id":"yearbook-tw-2023","title":"台灣企業永續發展年鑑 2023","description":"收錄台灣上市櫃公司 2023 年度 ESG 揭露成果，首次彙整 TCFD 四大支柱一致性揭露進度，並追蹤碳費草案對企業的衝擊與準備度。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["台灣","年鑑","永續報告","CSR","TCFD","碳費","FSC"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2023-12-31"},
  {"id":"yearbook-tw-2024","title":"台灣企業永續發展年鑑 2024","description":"收錄台灣上市櫃公司 2024 年度 ESG 揭露成果，正式導入 IFRS S1/S2 揭露嘗試與軌跡分析，聚焦 CBAM 申報數據與綠電採購揭露。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["台灣","年鑑","永續報告","CSR","IFRS S1","IFRS S2","CBAM","綠電"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2024-12-31"},
  {"id":"yearbook-tw-2025","title":"台灣企業永續發展年鑑 2025","description":"收錄台灣上市櫃公司 2025 年度 ESG 揭露成果，彙整金管會強制申報上路後首年之合規缺口、確信報告品質與同業標竿比較分析。","category":"industry-report","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["台灣","年鑑","永續報告","CSR","強制申報","確信","標竿"],"source":"https://www.twse.com.tw/zh/page/esg/","published_date":"2025-12-31"},
  {"id":"bench-global-2021","title":"Global Benchmark: Microsoft Carbon Negative by 2030","description":"International exemplar: Microsoft committed to be carbon negative by 2030 and remove all carbon emitted since 1975 by 2050.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["International","Benchmark","Carbon Negative","Technology"],"source":"https://www.microsoft.com/en-us/sustainability/","published_date":"2021-01-01"},
  {"id":"bench-global-2022","title":"Global Benchmark: Ørsted Transformation to Renewable Energy","description":"International exemplar: Ørsted transformed from fossil fuel to world's largest offshore wind developer.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["International","Benchmark","Renewable Energy","Offshore Wind","SBTi"],"source":"https://orsted.com/en/Sustainability","published_date":"2022-01-01"},
  {"id":"bench-tw-2023","title":"Taiwan Benchmark: TSMC Renewable Energy & Supply Chain Decarbonization","description":"Taiwan leading enterprise: TSMC committed to net-zero by 2050 and renewable energy exceeded 40% in 2023.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["Taiwan","Benchmark","TSMC","Renewable Energy","Net-Zero","Supply Chain"],"source":"https://www.tsmc.com","published_date":"2023-01-01"},
  {"id":"bench-tw-2024","title":"Taiwan Benchmark: Cathay Financial Holdings ESG Integration","description":"Taiwan leading enterprise: Cathay Financial integrates ESG into investment decisions and insurance products.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Governance","tags":["Taiwan","Benchmark","Finance","ESG Integration"],"source":"https://www.cathayholdings.com","published_date":"2024-01-01"},
  {"id":"bench-global-2024","title":"Global Benchmark: IKEA Circular Economy & Climate Positive","description":"International exemplar: IKEA committed to becoming climate positive by 2030.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["International","Benchmark","Circular Economy","Retail","Renewable Energy"],"source":"https://www.ikea.com","published_date":"2024-01-01"},
  {"id":"bench-tw-2025","title":"Taiwan Benchmark: ASE Technology Holdings Water Stewardship","description":"Taiwan leading enterprise: ASE achieved water neutrality at major facilities.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Environmental","tags":["Taiwan","Benchmark","ASE","Water Stewardship","Semiconductor"],"source":"https://www.aseglobal.com","published_date":"2025-01-01"},
  {"id":"bench-global-2025","title":"Global Benchmark: Uniqlo (Fast Retailing) Sustainable Supply Chain","description":"International exemplar: Uniqlo leads textile sustainability with recycling and responsible sourcing.","category":"case-study","file_url":None,"gri_reference":None,"esg_category":"Social","tags":["International","Benchmark","Retail","Textile","Supply Chain","Recycling"],"source":"https://www.uniqlo.com","published_date":"2025-01-01"}
]

ok = 0
for doc in docs:
    r = requests.post(f"{rest}/reading_room_documents", headers={**headers, 'Prefer': 'return=representation'}, json=[doc])
    if r.status_code in (200, 201):
        ok += 1
        print('OK ', doc['id'])
    elif r.status_code == 409 or 'duplicate' in r.text.lower() or 'already exists' in r.text.lower():
        print('EXISTS', doc['id'])
    else:
        print('FAIL', doc['id'], r.status_code, r.text[:120])

print(f'\nDone. {ok} inserted out of {len(docs)}')
