var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/webhook/ncbdb/route.js")
R.c("server/chunks/_1-ma4oh._.js")
R.c("server/chunks/src_shared_types_1mr9gp2._.js")
R.c("server/chunks/[root-of-the-server]__1x_gphc._.js")
R.c("server/chunks/lib_10qmkmt._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__0w_t_vy._.js")
R.c("server/chunks/[root-of-the-server]__1nz2fiy._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/node_modules_15ff9zg._.js")
R.c("server/chunks/[root-of-the-server]__0y6567a._.js")
R.c("server/chunks/lib_firebase_ts_17mhq4o._.js")
R.c("server/chunks/node_modules_zod_v3_1h7_2ut._.js")
R.c("server/chunks/node_modules_@noble_secp256k1_index_1n_z1ce.js")
R.c("server/chunks/_next-internal_server_app_api_webhook_ncbdb_route_actions_09ihwm_.js")
R.m(874527)
module.exports=R.m(874527).exports
