var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/sustain-write/route.js")
R.c("server/chunks/[root-of-the-server]__07mz7aj._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/lib_esg_gri-expert-templates-store_ts_1hya-pe._.js")
R.c("server/chunks/[root-of-the-server]__0y6567a._.js")
R.c("server/chunks/node_modules_15ff9zg._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_next-internal_server_app_api_sustain-write_route_actions_1u5cndr.js")
R.m(286529)
module.exports=R.m(286529).exports
