// This file is automatically generated. Do not edit manually.

export interface AgentSkill {
  id: string;
  agent_id: string;
  skill_id: string;
  enabled?: number | null;
  custom_config?: string | null;
  assigned_at?: string | null;
}

export interface Agent {
  id: string;
  name: string;
  description?: string | null;
  system_prompt?: string | null;
  base_model?: string | null;
  temperature?: number | null;
  max_tokens?: number | null;
  context_strategy?: string | null;
  metadata?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface EmissionFactor {
  id: string;
  category?: string | null;
  sub_category?: string | null;
  name: string;
  unit?: string | null;
  factor?: number | null;
  source?: string | null;
  region?: string | null;
  year?: number | null;
  uncertainty?: number | null;
  created_at?: string | null;
}

export interface GameBattleHistory {
  id: string;
  player_id: string;
  opponent_id?: string | null;
  result?: string | null;
  score?: number | null;
  timestamp?: string | null;
}

export interface GamePlayer {
  id: string;
  username: string;
  level?: number | null;
  xp?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface GovernanceProposal {
  id: string;
  title: string;
  description?: string | null;
  proposer_id?: string | null;
  status?: string | null;
  expires_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface Incident {
  id: string;
  title: string;
  description?: string | null;
  type?: string | null;
  severity?: string | null;
  status?: string | null;
  occurred_at?: string | null;
  location?: string | null;
  reported_by?: string | null;
  org_unit_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface KnowledgeBase {
  id: string;
  name: string;
  description?: string | null;
  agent_id?: string | null;
  total_chunks?: number | null;
  total_size_bytes?: number | null;
  embedding_model?: string | null;
  metadata?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface MarketIntelligenceItem {
  id: string;
  source_id?: string | null;
  title: string;
  url?: string | null;
  summary?: string | null;
  published_at?: string | null;
  sentiment?: string | null;
  content?: string | null;
  impact_score?: number | null;
  crawled_at?: string | null;
  tags?: string | null;
  created_at?: string | null;
}

export interface MarketIntelligenceSource {
  id: string;
  name: string;
  url?: string | null;
  category?: string | null;
  description?: string | null;
  frequency?: string | null;
  reason?: string | null;
  is_active?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface MediaAsset {
  id: string;
  filename: string;
  url: string;
  type?: string | null;
  size?: number | null;
  uploaded_by?: string | null;
  created_at?: string | null;
}

export interface MemoryChunk {
  id: string;
  kb_id?: string | null;
  content: string;
  embedding?: string | null;
  metadata?: string | null;
  source?: string | null;
  chunk_index?: number | null;
  parent_document_id?: string | null;
  created_at?: string | null;
}

export interface MetricDefinition {
  id: string;
  code: string;
  name: string;
  unit?: string | null;
  description?: string | null;
  category?: string | null;
  calculation_method?: string | null;
  created_at?: string | null;
}

export interface OrgUnit {
  id: string;
  name: string;
  type?: string | null;
  parent_id?: string | null;
  path?: string | null;
  level?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface OutboxEvent {
  id: string;
  aggregatetype: string;
  aggregateid: string;
  type: string;
  payload: string;
  timestamp?: string | null;
}

export interface SchemaBackup {
  id: string;
  schema_snapshot?: string | null;
  created_at?: string | null;
}

export interface SensorReading {
  id: string;
  sensor_id: string;
  type?: string | null;
  value?: number | null;
  unit?: string | null;
  timestamp?: string | null;
  metadata?: string | null;
  created_at?: string | null;
}

export interface Skill {
  id: string;
  name: string;
  description?: string | null;
  category?: string | null;
  requires_hitl?: number | null;
  implementation_code?: string | null;
  parameters_schema?: string | null;
  enabled?: number | null;
  usage_count?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface SustainabilitySource {
  id: string;
  source_id?: number | null;
  name_en?: string | null;
  name_tc?: string | null;
  url?: string | null;
  category?: string | null;
  category_name?: string | null;
  content_type?: string | null;
  update_frequency?: string | null;
  priority?: number | null;
  rationale?: string | null;
  is_active?: number | null;
  last_crawled_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface Database {
  public: {
    Tables: {
      agent_skills: {
        Row: AgentSkill;
        Insert: AgentSkill;
        Update: Partial<AgentSkill>;
      };
      agents: {
        Row: Agent;
        Insert: Agent;
        Update: Partial<Agent>;
      };
      emission_factors: {
        Row: EmissionFactor;
        Insert: EmissionFactor;
        Update: Partial<EmissionFactor>;
      };
      game_battle_history: {
        Row: GameBattleHistory;
        Insert: GameBattleHistory;
        Update: Partial<GameBattleHistory>;
      };
      game_players: {
        Row: GamePlayer;
        Insert: GamePlayer;
        Update: Partial<GamePlayer>;
      };
      governance_proposals: {
        Row: GovernanceProposal;
        Insert: GovernanceProposal;
        Update: Partial<GovernanceProposal>;
      };
      incidents: {
        Row: Incident;
        Insert: Incident;
        Update: Partial<Incident>;
      };
      knowledge_bases: {
        Row: KnowledgeBase;
        Insert: KnowledgeBase;
        Update: Partial<KnowledgeBase>;
      };
      market_intelligence_items: {
        Row: MarketIntelligenceItem;
        Insert: MarketIntelligenceItem;
        Update: Partial<MarketIntelligenceItem>;
      };
      market_intelligence_sources: {
        Row: MarketIntelligenceSource;
        Insert: MarketIntelligenceSource;
        Update: Partial<MarketIntelligenceSource>;
      };
      media_assets: {
        Row: MediaAsset;
        Insert: MediaAsset;
        Update: Partial<MediaAsset>;
      };
      memory_chunks: {
        Row: MemoryChunk;
        Insert: MemoryChunk;
        Update: Partial<MemoryChunk>;
      };
      metric_definitions: {
        Row: MetricDefinition;
        Insert: MetricDefinition;
        Update: Partial<MetricDefinition>;
      };
      org_units: {
        Row: OrgUnit;
        Insert: OrgUnit;
        Update: Partial<OrgUnit>;
      };
      outbox_events: {
        Row: OutboxEvent;
        Insert: OutboxEvent;
        Update: Partial<OutboxEvent>;
      };
      schema_backups: {
        Row: SchemaBackup;
        Insert: SchemaBackup;
        Update: Partial<SchemaBackup>;
      };
      sensor_readings: {
        Row: SensorReading;
        Insert: SensorReading;
        Update: Partial<SensorReading>;
      };
      skills: {
        Row: Skill;
        Insert: Skill;
        Update: Partial<Skill>;
      };
      sustainability_sources: {
        Row: SustainabilitySource;
        Insert: SustainabilitySource;
        Update: Partial<SustainabilitySource>;
      };
    };
  };
}