var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/omni-agent/notes/route.js")
R.c("server/chunks/[root-of-the-server]__1aimdz_._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/node_modules_zod_v3_0h7h7rc._.js")
R.c("server/chunks/[root-of-the-server]__0y6567a._.js")
R.c("server/chunks/node_modules_15ff9zg._.js")
R.c("server/chunks/node_modules_1ssowgd._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/_next-internal_server_app_api_omni-agent_notes_route_actions_03wlf-s.js")
R.m(902827)
module.exports=R.m(902827).exports
