var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/compliance-check/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1s185xn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1intm3w.js")
R.c("server/chunks/ssr/[root-of-the-server]__087nj0h._.js")
R.c("server/chunks/ssr/node_modules_0c4h-pv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15ohnpm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/app_global-error_tsx_113y3za._.js")
R.c("server/chunks/ssr/_next-internal_server_app_compliance-check_page_actions_1l6riku.js")
R.m(473550)
module.exports=R.m(473550).exports
